### ISSUE TITLE
Neo4j JDBC error 

### ISSUE THREAD

**Issue by kaniika31** [neo4j-contrib/neo4j-apoc-procedures#1061]
Hi , 

I am trying to run 👍 

call apoc.load.driver('oracle.jdbc.driver.OracleDriver');

in neo4j to load oracle driver but i am getting below error 

Neo.ClientError.Procedure.ProcedureCallFailed: Failed to invoke procedure `apoc.load.driver`: Caused by: java.lang.RuntimeException: Could not load driver class oracle.jdbc.driver.OracleDriver oracle.jdbc.driver.OracleDriver

I have placed the jdbc and apoc in plugins and i am able to apoc.load.driver procedure on command prompt . 

Please help me with the issue

**Comment by kaniika31** [comment]
1. When i am running below command ..

CALL apoc.load.jdbc('jdbc:oracle:thin:@localhost:1521:oracle,sys,oracle@123',null);

I am getting this error .

Neo.ClientError.Procedure.ProcedureCallFailed: Failed to invoke procedure `apoc.load.jdbc`: Caused by: java.lang.NullPointerException

And when i run this .

CALL apoc.load.jdbc('jdbc:oracle:thin:system/neo4j@localhost:1521:oracle','select * from artists') YIELD row
CREATE (n:Artists {name:row.title})

I get this error...

Neo.ClientError.Procedure.ProcedureCallFailed: Failed to invoke procedure `apoc.load.jdbc`: Caused by: java.sql.SQLException: No suitable driver found for jdbc:oracle:thin:system/neo4j@localhost:1521:oracle

Have downloaded and added ojdbc and neo4j driver in plugin . 

Not sure where it is going wrong .

**Comment by kaniika31** [comment]
Hi All , 

Driver issues is resolved i guess .
Now when i am giving below syntax , i am getting a different error 

CALL apoc.load.jdbc("jdbc:oracle:thin:system/oracle123@localhost:1521:ORACLE",'select * from artists') YIELD row
CREATE (n:artists {name:row.title})

ERROR 

Neo.ClientError.Procedure.ProcedureCallFailed: Failed to invoke procedure `apoc.load.jdbc`: Caused by: java.sql.SQLException: JDBC URL is not correct.
A valid URL format is: 'jdbc:neo4j:http://<host>:<port>'

Please let me know the correct syntax to connect to my oracle database residing in my local system .

**Comment by conker84** [comment]
Hi @kaniika31,
I think the JDBC url is malformed can you try with this: `jdbc:oracle:thin:system/oracle123@localhost:1521/ORACLE`

**Comment by conker84** [comment]
And please remove all the neo4j-jdbc jars

**Comment by kaniika31** [comment]
Hi , 

Tried this...
Got this error 
<img width="806" alt="jdbc issue" src="https://user-images.githubusercontent.com/46993083/52112980-125dd080-262e-11e9-8580-c703c1e5b712.PNG">

**Comment by kaniika31** [comment]
Note that , this is oracle's database username and password .

**Comment by inserpio** [comment]
@kaniika31 that issue is raised by the neo4j-jdbc driver.
Please remove any neo4j-jdbc jar and configuration pointing to that.
neo4j-jdbc and neo4j-apoc are completely separated projects, meant for different use cases.
The apoc.load.jdbc uses the jdbc interface to get the data from a relational database (oracle for you) and the only think you need to have and configure is an *oracle* jdbc driver.
The neo4j-jdbc driver is used to talk with neo4j via the jdbc interface, so if you're writing a program in java and you like to use the old plain jdbc approach then you can with this neo4j-jdbc driver (typically we use it to let third party tools interact with neo4j via the classic jdbc api).
Hope I clarified a bit more the difference between the two projects.

**Comment by kaniika31** [comment]
Thanks jexp ..
Also , Please let me know if after synchronizing my Oracle Database with Neo4j , is there is any possibility 
of copying/inserting the data from Oracle to Neo4j Database ??
