### ISSUE TITLE
apoc.periodic.commit should check for `limit` 

### ISSUE THREAD

**Issue by sarmbruster** [neo4j-contrib/neo4j-apoc-procedures#1071]
if the statement passed in as an argument does not contain the word `limit`, it should fail with a reasonable error message.

**Comment by WyrdNexus** [comment]
While the potential for breakingly large sets is possible here, I don't agree with the framing of this problem, nor the solution. 

1. There are many different methods of retrieving a set of data to operate on which preclude the use of a LIMIT clause, like functions and procedures. "Should check for limit," assumes _only_ operating with MATCH/MERGE sets. 
2. "Check the command for the string, 'limit'" is weak enforcement in the expected case, and enforces artificially adding a limit clause (or a comment /* limit */) into the command for other cases.
3. Use cases operating on the results of MATCH/MERGE sets, or those which _should_ and _could_ include a LIMIT clause, should be using `apoc.periodic.iterate` rather than `apoc.periodic.commit`.

Wonderful aspiration to try to save users from breaking ram, and crashing Neo4j. Unfortunately, any kind of enforcement on a string passed as a command, will either require an interpreter, a compiler, or will impose unintended restrictions.
