### ISSUE TITLE
Enhance Path Expander beginSequenceAtStart to affect terminatorNodes (and other node filters)

### ISSUE THREAD

**Issue by zakjan** [neo4j-contrib/neo4j-apoc-procedures#1220]
## Feature description

Enhance Path Expander `beginSequenceAtStart` to affect `terminatorNodes` (and other node filters)

Rationale: if start and terminator nodes are the same, currently path expander doesn't return any paths, it returns only the start nodes.

Sample:

```
CREATE
    (a:Outer {name: 'A'}),
    (b:Outer {name: 'B'}),
    (c:Outer {name: 'C'}),
    (x:Inner {name: 'X'}),
    (y:Inner {name: 'Y'}),
    (z:Inner {name: 'Z'}),
    (a)-[:TO]->(x),
    (b)-[:TO]->(y),
    (c)-[:TO]->(z),
    (x)-[:TO]->(y),
    (y)-[:TO]->(z),
    (z)-[:TO]->(x)

// returns only start nodes, no paths
MATCH (n:Outer) WITH collect(n) AS nodes
CALL apoc.path.expandConfig(nodes, {
    terminatorNodes: nodes,
    maxLevel: 10
}) YIELD path AS p
RETURN p

// currently also returns only start nodes, no paths
// could be enhanced to return paths
MATCH (n:Outer) WITH collect(n) AS nodes
CALL apoc.path.expandConfig(nodes, {
    terminatorNodes: nodes,
    maxLevel: 10,
    beginSequenceAtStart: false
}) YIELD path AS p
RETURN p
```

## Considered alternatives

Unwinding start nodes and filtering the start node from terminator nodes manually works, it returns paths:

```
MATCH (n:Outer) WITH collect(n) AS nodes
UNWIND nodes AS n
WITH n, [m IN nodes WHERE n <> m] AS terminatorNodes
CALL apoc.path.expandConfig(n, {
    terminatorNodes: terminatorNodes,
    maxLevel: 10
}) YIELD path AS p
RETURN p
```

However it feels unnatural, if there is already `beginSequenceAtStart` param, which is meant to work similarly, it just doesn't support combination with `terminatorNodes` (and other node filters) yet.

Also this alternative might have performance implications.

## How this feature can improve the project?

Simplify searching for all paths between given nodes with path expander capabilities.

**Comment by InverseFalcon** [comment]
Hello,

While we can demonstrate some things to improve with what you've provided, there are a few things to correct in the assumptions here.

This doesn't have anything to do with `beginSequenceAtStart`, as there are no sequences involved here. I think you meant to cite `filterStartNode` (whose default is false), as this is the config property that toggles whether filters should apply to the start node.

Note that this does work as expected when we use label filters instead. Your query is such that you want to start from all :Outer nodes with all :Outer nodes as terminator nodes. We can substitute the terminator nodes for a labelFilter applying a termination filter on nodes of an :Outer label:

```
MATCH (n:Outer) WITH collect(n) AS nodes
CALL apoc.path.expandConfig(nodes, {labelFilter:'/Outer',
    maxLevel: 10
}) YIELD path AS p
RETURN p
```

This should return the expected paths.

If we toggle filterStartNodeTrue then we get a minimal result, starting and ending on the start nodes:

```
MATCH (n:Outer) WITH collect(n) AS nodes
CALL apoc.path.expandConfig(nodes, {labelFilter:'/Outer',
    maxLevel: 10,
    filterStartNode:true
}) YIELD path AS p
RETURN p
```

Using this same query, if we add minLevel:1 then the termination filter doesn't apply, and we get the expected path results.

So the two things to fix here:

Make `terminatorNodes` behave like the termination filter in the `labelFilter`, such that 

1. the `filterStartNode` value should apply (if false then we will not check if the start node is a terminator node)

2. if below `minLevel` we should not apply the terminatorNodes check.

**Comment by zakjan** [comment]
Indeed, thanks for the correction, I actually couldn't understand from documentation the difference between `beginSequenceAtStart` and `filterStartNode`, and while I experimented heavily with path expanders, I used lots of various configurations.

Is there a case when having these two params separate is useful, or would it make sense to merge them together?

**Comment by InverseFalcon** [comment]
It should work with sequences when fixed. But there is a bit of an outstanding question here that I'll get to in a second.

The difference of the properties is that `filterStartNode` determines whether or not the starting node of the expansion needs to be subject to all of the filtering we enforce on the other nodes.

For example, if we use the movies graph and start from Keanu Reeves like this:

```
MATCH (p:Person {name:'Keanu Reeves'})
CALL apoc.path.expandConfig(p, {maxLevel:1, labelFilter:'-Person', filterStartNode:true}) YIELD path
RETURN last(nodes(path))
```

Since filterStartNode is true, it's subject to the filtering from the labelFilter, which currently has a blacklist on :Person nodes, so we would get no results since Keanu, our starting node, is a :Person. 

If we set `filterStartNode:false` or left off the property (since the default is false) then the starting node wouldn't be subject to filtering, so it wouldn't get caught by the blacklist.

The same would apply to usage of the termination label filter `/` on stopping expansion when reaching a node with that label, or the whitelist filter `+` (or just the label without the symbol), in case the starting node didn't have any label in the whitelist.

All that behavior works. What doesn't work is applying the whitelistNodes, blacklistNodes, endNodes, or terminationNodes logic to respect `filterStartNode`.

The config property `beginSequenceAtStart` has a different purpose. This controls where the sequence actually starts. It could be that we start the sequence at the start node, which is default. Or it could be that we start a sequence one-off from the starting node, so the starting node isn't considered a part of the sequence to be evaluated.

**Comment by zakjan** [comment]
Ok thanks, I'm looking forward to filterStartNode to support terminatorNodes

**Comment by InverseFalcon** [comment]
I've opened #1289 which covers all of the related behaviors needing fixing for this.

Please track it there, I'm going to close this one up.

**Comment by zakjan** [comment]
Thanks!
