### ISSUE TITLE
Custom Procedures Timer cancelled error

### ISSUE THREAD

**Issue by jexp** [neo4j-contrib/neo4j-apoc-procedures#1299]
Not sure if this is being tracked in the right place but we have several instances failing to come up (they come up eventually) due to "Timer already cancelled". 

Find attached logs from one such instance. Not sure if it is relevant but we kill instances (kill -9 {pid}) which then get restarted.

In the logs you can see an occurrence at `2019-09-20 12:25:39`

"Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@349f0ca4' was successfully initialized, but failed to start. Please see the attached cause exception "Timer already cancelled.". Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@349f0ca4' was successfully initialized, but failed to start. Please see the attached cause exception "Timer already cancelled."

https://trello.com/c/8RtcNYij/1676-clusters-failing-to-come-up-with-timer-already-cancelled-after-being-killed-by-chaos-monkey

**Comment by jexp** [comment]
somehow `unavailable` might be called twice??

https://github.com/neo4j-contrib/neo4j-apoc-procedures/blob/3.5/src/main/java/apoc/custom/CypherProcedures.java#L366-L395

**Comment by Dcanzano** [comment]
@jexp   we are seeing the same under apoc-3.5.0.4-all.jar

**Comment by sarmbruster** [comment]
Since apoc 3.5.0.5 apoc no longer uses a Timer but instead relies on the neo4j internal scheduler service. I assume that due to this, that issue should be resolved in 3.5.0.5. @Dcanzano can you please verify this.
For reference, the commit applying the change was https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/183a0ee15fac3666ddd4454cfe2417ee7e71399d
