### ISSUE TITLE
apoc.export.csv.query Fails with No Such Method: JsonGenerator.writeArray

### ISSUE THREAD

**Issue by timholds** [neo4j-contrib/neo4j-apoc-procedures#1309]
## Guidelines

Please note that GitHub issues are only meant for bug reports/feature requests. If you have questions on how to use APOC, please ask on [the Neo4j Discussion Forum](https://community.neo4j.com/c/neo4j-graph-platform/procedures-apoc) instead of creating an issue here.

## Expected Behavior (Mandatory)
Exporting the results of a query to a file

## Actual Behavior (Mandatory)
`ClientError: Procedure Call Failed: Failed to invoke procedure `apoc.export.csv.query` : Caused by: java.lang.NoSuchMethodError: com.fasterxml.jackson.core.JsonGenerator.writeArray([DII)V`

### Steps (Mandatory)

  1. Run docker instance with the following config settings
![Screen Shot 2019-10-02 at 1 39 33 PM](https://user-images.githubusercontent.com/24782018/66067684-1e31c780-e51a-11e9-9bd7-8c240fcc5998.png)

  2. 
```
CALL apoc.export.csv.query('
        'MATCH (b) RETURN b',
        '/import/folder/subfolder/filename.csv', 
        {quotes:true});
```

## Specifications (Mandatory)

Currently used versions

### Versions

  - OS: Debian GNU/Linux 10 (buster)
  - Neo4j: 3.5.9 
  - Neo4j-Apoc: 3.4.0.7

Not sure why I am getting this error. When I change the directory to something else (for example `tmp/data/folder/subfolder/filename.csv` I get either permission denied or folder does not exist. However, in this one particular location that I want to write the file I get the jsonGenerator.writeArray error and I'm not sure why. 

Any ideas on why this is failing?

**Comment by alexiudice** [comment]
@timholds I've run into something similar and it was due to the actual apoc `.jar` file I was using. 

If the jar is called something like `apoc-3.4.0.7.jar` and is under 1mb in size then thats only the compiled apoc library without its required dependencies.

You'll want to use a jar thats been compiled with all the required dependencies. It would have a name like `apoc-3.4.0.7-all.jar` and should be about 20mb+ in size. If you already have a jar like this then it could be an apoc/neo4j versioning issue.

I was able to build my own apoc jars by pulling this repository, navigating to it (`/neo4j-apoc-procedures`) and running `./gradlew shadow`. This built the project with all needed dependencies, and output the jar I needed to the directory `/neo4j-apoc-procedures/build/libs/apoc-3.4.0.7-all.jar`.  You can then copy the jar to the neo4j/plugins you need. This fixed my "NoSuchMethod" issue.


Also I would recommend you update you're apoc version, since apoc version `3.4.0.7` expects a neo4j version of `3.4.x.x`.

**Comment by timholds** [comment]
@alexiudice Thank you for the response. I have upgraded APOC and now I have `apoc-3.5.0.3-all.jar` in the plugins folder at 14MB, but still having this problem.

**Comment by conker84** [comment]
@timholds Did you download the file from maven central?
Can you please download it from [here](https://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/download/3.5.0.5/apoc-3.5.0.5-all.jar)?

Looking forward to your feedback

**Comment by timholds** [comment]
@conker84 This fixes the issue.
Thank you!
