### ISSUE TITLE
Possible bug in apoc graphml export 

### ISSUE THREAD

**Issue by nabsabraham** [neo4j-contrib/neo4j-apoc-procedures#1449]
I think this is a bug in the `apoc.export.graphml.all` function. The keys in blue are generated to be the only unique ids but the keys in red for the actual graph use a key named 'labels' that was not generated in the unique id list. This is throwing off a graph viz tool that I am using downstream - how can this be fixed? 

![image](https://user-images.githubusercontent.com/36169471/76897988-2b920280-686b-11ea-8eae-aea9264856c8.png)

Tutorial from [here](https://neo4j.com/docs/labs/apoc/current/export/graphml/).

**Comment by jexp** [comment]
Thanks a lot for the report, yes, looks like a bug.

**Comment by jexp** [comment]
Currently you can only fix it by editing the file and fixing the `<key>` entry.

**Comment by nabsabraham** [comment]
thanks! I'll wait on your fix :)

**Comment by neocsbee** [comment]
I am also facing the same error. It appears to be an issue only with nodes. Haven't come across an issue with edges yet.

![image](https://user-images.githubusercontent.com/3037022/85408395-768a7880-b532-11ea-9729-692ce43992d2.png)

Along with fixing the <key> entry, is it possible to remove the ":" before the labels?
For example, in the above Football GraphGist case, "Player" and "Team" are labels instead of ":Player" and ":Team".

@jexp: Will follow your tip for fixing the <key> entry in the meantime.

**Comment by vga91** [comment]
Hi @nabsabraham, what graph viz tool did you use to test the graph? Thanks.
