### ISSUE TITLE
allSimplePaths (and other path algorithms) requires a cartesian join

### ISSUE THREAD

**Issue by dan-kez** [neo4j-contrib/neo4j-apoc-procedures#150]
At the moment the only way to use the function all Simple Paths is to have a Cartesian join between the starting and ending nodes which slows down a query without good reason.

e.g. 

```
MATCH (from:CITY), (to:AIRPORT)
CALL apoc.algo.allSimplePaths(from, to, 'ROAD', 3) yield path as path
RETURN path
```

I propose allowing an input of a list of ids so that you can do something like this:

```
MATCH (from:CITY)
with id(from) as fromids
MATCH (to:AIRPORT)
with fromids, id(to) as toids
CALL apoc.algo.allSimplePaths(fromids, toids, 'ROAD',3) yield path as path
RETURN path
```

Or even better (directly defining the labels between which to search:

```
CALL apoc.algo.allSimplePaths('+CITY',  '+AIRPORT', 'ROAD', 3) yield path as path
RETURN path
```

**Comment by jexp** [comment]
I don't understand, it shouldn't make a difference.

You probably meant this (you missed collect).

```
MATCH (from:CITY)
with collect(from) as fromNodes
MATCH (to:AIRPORT)
with fromNodes, collect(to) as toNodes
CALL apoc.algo.allSimplePaths(fromNodes, toNodes, 'ROAD',3) yield path as path
RETURN path
```

Your two lists of id's still form a cross product that have to be checked against.

What's the use-case for checking two sets of nodes against each other?

But we can definitely consider passing in lists of nodes and ids.
If we do that we should do it for the other algorithms too.

**Comment by dmk255** [comment]
Maybe I'm missing something but allSimplePaths does not take a collection of nodes (getting the below error)
```
Type mismatch: expected Node but was Collection<Node> (line 6, column 31 (offset: 155))
"CALL apoc.algo.allSimplePaths(fromNodes,toNodes,'ROAD',3) YIELD path as path"
```

The case listed above is a basic example I made up. My case is that I have two subsets of one label and I need to find all nodes that I can reach from either direction:
e.g.
(a:LABELA)->(b)->(c)->(d)
(d:LABELB)->(e)->(c)->(a)

From the nodes of these two paths I need to find the common nodes [(a),(d),(c)] as those nodes 'inherit'; both LABELA and LABELB.

I've done something like this with the following query but it's slower since it repeats nodes (not useful in my case since I'm trying to get the distinct nodes):
```
profile 
MATCH path=((footabs:tabBIZ:FOO)-[:TABLEFOREIGNKEY *..3]->(n:tabBIZ))
	UNWIND nodes(path) as allfoonodes
WITH collect(distinct(allfoonodes)) as foonodes
MATCH path=((bartabs:tabBIZ:BAR)-[:TABLEFOREIGNKEY *..3]->(n2:tabBIZ))
	UNWIND nodes(path) as allbarnodes
WITH  foonodes, collect(distinct(allbarnodes)) as barnodes
CALL apoc.coll.intersection(foonodes,barnodes) yield value as biznodes
RETURN size(foonodes),size(barnodes),size(biznodes)
```

I'd use allSimplePaths but since it requires a Cartesian join it ends up being slower than the above.

**Comment by dmk255** [comment]
@jexp Are there any thoughts on allowing a collection of nodes as in your above example?

**Comment by conker84** [comment]
We close this as for algos we have a different library
