### ISSUE TITLE
APOC couln't set a URLStreamHandlerFactory message always there as of apoc 4.1.0.0 - neo4j 4.1.0 

### ISSUE THREAD

**Issue by tomgeudens** [neo4j-contrib/neo4j-apoc-procedures#1571]
## Expected Behavior
If there are no other JVMs running, APOC should be able to set a URLStreamHandlerFactory.

## Actual Behavior 
As of Neo4j 4.1.0 EE, APOC 4.1.0.0, APOC is unable to set the URLStreamHandlerFactory and throws a message when Neo4j starts up.

**APOC couln't set a URLStreamHandlerFactory since some other tool already did this (e.g. tomcat). This means you cannot use s3:// or hdfs:// style URLs in APOC. This is caused by a limitation of the JVM which we cannot fix.**

B.t.w. also note the typo in the **couln't**, that should be **couldn't** :-)

### Steps
Follow basic install that you can find at (for Linux and Windows respectively)
https://tiny.cc/neo4j-linux-setup
https://tiny.cc/neo4j-windows-setup

## Specifications
Currently used versions

### Versions

  - OS: Ubuntu 18.04 LTS, Windows 10
  - Neo4j: 4.1.0
  - Neo4j-Apoc: 4.1.0.0

**Comment by bbenzikry** [comment]
We also ran into this on the docker build with the official chart

**Comment by EnziinSystem** [comment]
Me too.

```
APOC couln't set a URLStreamHandlerFactory since some other tool already did this (e.g. tomcat). This means you cannot use s3:// or hdfs:// style URLs in APOC
```

**Comment by sarmbruster** [comment]
Can you please confirm that you have both `apoc-4.1.0.1-core.jar" *and* `apoc-4.1.0.1-all.jar` in your `plugins` folder.

If so remove the `-core` jar since the `-all` variant contains it.

If you have both on the classpath you'll see the error message mentioned since the JVM allows only once to call `setURLStreamHandler`.

**Comment by tomgeudens** [comment]
@sarmbruster **Only** apoc-4.1.0.1-all.jar is in the plugins folder. There is labs folder now with apoc-4.1.0.1-core.jar, but that one isn't used and should not interfere.

**Comment by su-park** [comment]
I have same issue with version 4.1.1
Is this issue solved?

# Actual Behavior
As of Neo4j 4.1.1, APOC 4.1.0.0-all, APOC is unable to set the URLStreamHandlerFactory and throws a message when Neo4j starts up.

`APOC couln't set a URLStreamHandlerFactory since some other tool already did this (e.g. tomcat). This means you cannot use s3:// or hdfs:// style URLs in APOC. This is caused by a limitation of the JVM which we cannot fix.
`
# Versions
OS: Mac OS Catalina Version 10.15.13
Neo4j: 4.1.1
Plugins: Neo4j-Apoc: 4.1.0.0-all, neo4j-graph-data-science-1.3.2-standalone.jar

# More specifications
because of malfunction, I installed Neo4j (3.5.21) and plugins (apoc, gds) and it works best.
