### ISSUE TITLE
register functions / procedures 

### ISSUE THREAD

**Issue by jexp** [neo4j-contrib/neo4j-apoc-procedures#163]
call apoc.register.procedure/function(name,{param:type},return-type,cypher)

**Comment by vic** [comment]
Could you add a bit more details ? and maybe an example?

If I understand correctly would this allow you to call any Java (static)method from cypher? If so, that would be awesome for calling simple libraries, eg, one use case for me would be to call [geohash](https://github.com/davidmoten/geo) functions without having to create another server plugin just for it. Am I understanding what this issue is all about ? If so I'd really like to make it real.

**Comment by vic** [comment]
Oh my bad you were referring to Neo4J user-defined functions like [from this post](http://jexp.de/blog/2016/10/user-defined-functions-in-neo4j-3-1-0-m10/).

Anyways, would you think a procedure/function to call a POJO method (via reflection) would be useful for calling simple Java libs ?

**Comment by jexp** [comment]
Sounds like an interesting feature, good idea.
We just have to make sure that the security implications are taken care of. Can you create a separate issue for that suggestion?

This idea was to turn cypher fragments into a procedure or function, so you get reusable snippets.
Those would be also executed with the compiled runtime so it would become quite effective.

**Comment by conker84** [comment]
This was fixed by Cypher Procedures
