### ISSUE TITLE
add apoc.load.folder("pattern", recursive=true/false) yield url

### ISSUE THREAD

**Issue by jexp** [neo4j-contrib/neo4j-apoc-procedures#1639]
Allow to load the "import" folder recursively so if there are multiple nested files in directories you can get them all

so you could then use 

```
call apoc.load.folder("*.csv", true) yield url
load csv with headers from url as row ....

```

**Comment by jexp** [comment]
Should be pretty quick to implement.

**Comment by jexp** [comment]
So that we don't need a local script/server like Adam used here: https://medium.com/neo4j/how-to-create-a-knowledge-graph-from-your-slack-archive-with-neo4j-6a1a1d59a535

**Comment by conker84** [comment]
@jexp @mneedham 
I have the idea to create also a second procedure `apoc.load.folder.async(<pattern>, <cypher>, <conf>)` that basically gets activated every time there is a file system change so in that case the cypher query gets invoked.
We can easily leverage the [WatchService](https://docs.oracle.com/javase/8/docs/api/java/nio/file/WatchService.html) of java in order to do that; providing a set of configuration parameters in order to manage the type of FS change the user wants to match. 
WDYT?

**Comment by mneedham** [comment]
Sounds like a good idea - would `apoc.load.folder.async` create a schedule task/job that gets tracked by the triggers stuff, or is it a separate thing? https://neo4j.com/labs/apoc/4.1/background-operations/triggers/

**Comment by conker84** [comment]
We need to create a background thread in order to manage the `WatchService` and we can use the same approach of triggers in order to manage its lifecycle but, yes it's a separate thing.
