### ISSUE TITLE
apoc.load.html procedure fail silently

### ISSUE THREAD

**Issue by tomasonjo** [neo4j-contrib/neo4j-apoc-procedures#1793]
Currently, the `apoc.load.html` procedure returns an error and rolls back the transaction if any error occurs. The error messaging is not really helpful, you can look at https://github.com/neo4j-contrib/neo4j-apoc-procedures/blob/4.1/full/src/main/java/apoc/load/LoadHtml.java#L54.
In my opinion, it would be better to fail silently and just return an empty map with defined keys. Something along the line of:

```
  query.keySet().stream().forEach(key -> {
      output.put(key, empty map);
  });
```

**Comment by conker84** [comment]
@tomasonjo can you provide a simple example in order to create a test case?

**Comment by tomasonjo** [comment]
The example call is

```
CALL apoc.load.html('https://edition.cnn.com/world',{a:'a'})
```

Maybe also the underlying problem can be fixed :)

**Comment by vga91** [comment]
@tomasonjo

[apoc-4.1.0.6.zip](https://github.com/neo4j-contrib/neo4j-apoc-procedures/files/6034758/apoc-4.1.0.6.zip)

I attached a jar with the "fail silently" feature. Now, with config `{failsSilently: true}`, the procedure doesn't fail with exception, but continue and create a Neo4j `log.warn` with the failed tag, for example 
```
WARN  Error during parsing element: <a hre f="#cite_ref-Simpson2018_1-0"><sup><i><b>a</b></i></sup></a>
```
and returns the list of the values, except for values not correctly parsed.
Otherwise, with `{failsSilently: false}` (default value), the procedure fails with an error like this:
```
Failed to invoke procedure `apoc.load.html`: Caused by: java.lang.RuntimeException: Error during parsing element: <a hre f="#cite_ref-Simpson2018_1-0"><sup><i><b>a</b></i></sup></a>
```



I created a pr with this change #1817

**Comment by tomasonjo** [comment]
Looks really nice!
