### ISSUE TITLE
Request: apoc.path.expand. Option to assume unlisted labels are whitelisted

### ISSUE THREAD

**Issue by dan-kez** [neo4j-contrib/neo4j-apoc-procedures#181]
At the moment if you supply a labelFilter any non-listed labels are assumed to be black listed. I think having an option to assume that all non listed labels are white listed and only specify black listed labels / end labels would be a benefit to the function (or its config cousin).

**Comment by jexp** [comment]
But if you supply a label filter do you just want to a exclude a few?

Perhaps we can do a +* or -* to control if it is blacklist or whitelist by default?

**Comment by InverseFalcon** [comment]
I'm guessing that this was submitted with the assumption that the labelFilter supports multiple operations at once (+, -, /) instead of only one at a time.

Currently the label filter only allows one operation, the one specified on the very first label of the filter. 

This means for a blacklist filter, anything not in the blacklist is allowed, and for the end node label filter, anything not in the end node filter is allowed as a component of a path leading up to an end node, but will never be the end node of a returned path.

#317 is a proposed improvement to allow multiple operations in the filter at once, and addresses the idea that if using an end-node label filter or a blacklist label filter (either alone or in combination with each other), that an empty whitelist should be interpreted as allowing all instead of disallowing all.

Otherwise, if there is a non-empty whitelist label filter, it should probably still exclude any nodes not in the whitelist.

There is still ambiguity regarding multi-labeled nodes where its labels fall within multiple label filters, that's up for discussion in #317 .

**Comment by InverseFalcon** [comment]
To summarize, I don't think this is a real issue in current implementation, and the concern is being addressed in the work done on allowing multiple label filter operations instead of just one.
