### ISSUE TITLE
Separate modules

### ISSUE THREAD

**Issue by cheerfulstoic** [neo4j-contrib/neo4j-apoc-procedures#19]
Would it be easy to separate out the groups of procs into modules that you could install separately, instead of one big bunch?

Is this even a problem?  Is there a lot of overhead to installing apoc, even as it grows?

**Comment by tkroman** [comment]
+1. And if future versions of neo4j will allow for the procedures to be hot-swapped (DB-restart-free procedure loading), OSGI-fying these packages would be cool, too.

**Comment by jexp** [comment]
Actually it is intentionally one single module

So that non-tech users don't have to fiddle around with multiple modules

Also multiple modules can't share dependencies as everything is loaded *only* from the procedure's jar.

There is zero overhead, you just drop the apoc jar into the plugins directory, done.

**Comment by jexp** [comment]
There will be no OSGi

There will be some hot reloading in the future.

I really want to minimize any complication for users, and tracking which "packages" they already installed or not and which versions etc. will just be a pain for them. That's why for the mid-term, I want to keep it all in one.

**Comment by cheerfulstoic** [comment]
That makes sense.  Maybe at some point Neo4j should have a plugin/package manager like rubygems/npm/etc...
