### ISSUE TITLE
apoc.meta.graph does not display relationships

### ISSUE THREAD

**Issue by rohankharwar** [neo4j-contrib/neo4j-apoc-procedures#192]
Hi 

When I run apoc.meta.graph(), i don't see the relationships but just the nodes. 
I have run this stored procedure on a small sample Movie database or a even on a graph of 400 MB DB size. 
So not sure if this is a defect. 

Here is a snapshot of how the output. 

![image](https://cloud.githubusercontent.com/assets/13203910/19867195/17b12afa-9f71-11e6-8c2f-688488663ebe.png)

Thanks,
Rohan

**Comment by jexp** [comment]
What Neo4j version. Did you try shift-reload? Any JS console outputs?

**Comment by rohankharwar** [comment]
Hi Michael, 
I guess that was it. I cleared my cache and fixed it. 

Thanks,
Rohan

**Comment by guglielmo** [comment]
I was experiencing the same issue. 
Neo4j version is 3.0.6. 
Apoc was built from source code, after cloning the master branch.

The error was due to a mis-use of the Apoc 1.x release in the new >3.0.4 neo4j version.
The results of the call were stored in the local cache.
Without deleting the whole browser's cache, you can remove the Local Storage (at least in the Chrome inspector), and the relations appear again.

**Comment by jexp** [comment]
It's a browser caching issue. Unrelated to apoc. Do eitehr shift-reload or
clear cache in the browser inspector (or disable cache, reload, enable cache)
