### ISSUE TITLE
Don't support relationship indexes in apoc.export.cypher.all

### ISSUE THREAD

**Issue by alizadehei** [neo4j-contrib/neo4j-apoc-procedures#2048]
Hi
I tried to export the database using the following query:

`CALL apoc.export.cypher.all("db.cypher",{format: "neo4j-shell", useOptimizations: {type: "UNWIND_BATCH",unwindBatchSize: 20}})`
After running, I encountered the following error:

> Failed to invoke procedure 'apoc.export.cypher.all' :  Caused by: java.lang.IllegalStateException: This is not a node index.

It seems that the export procedure only supports node indexes. So what about the relationship indexes?
### Versions

  - OS: Linux 20.04
  - Neo4j: 4.3.1
  - Neo4j-Apoc: 4.2.0.4

**Comment by vga91** [comment]
@alizadehei 
Thanks for the feedback.
Just to let you know, for neo4j 4.3 you should use apoc `4.3.0.0`, not the `4.2.0.4`.
With this version full text rel-indexes are managed correctly,
however there is a problem with the `BTREE` indexes, 
because it does not give your error but exports the rel-indexes as if they were node-indexes.
This one will be resolved as soon as possible.

**Comment by alizadehei** [comment]
@vga91 
Your welcome. You are right. I used Apoc 4.3.0.0 at first but there was a problem. I added Apoc 4.3.0.0 to the project using the following maven dependency:
```
<!-- https://mvnrepository.com/artifact/org.neo4j.procedure/apoc -->
<dependency>
    <groupId>org.neo4j.procedure</groupId>
    <artifactId>apoc</artifactId>
    <version>4.3.0.0</version>
</dependency>

```
but, some functions did not exist in the apoc 4.3.0.0. Among these functions, we can mention cases such as Coll, Maps, Meta, Date, GraphRefactoring, Warmup , ...
