### ISSUE TITLE
I performed CALL apoc.load.csv('test.csv') yield lineNo, map, list RETURN *

### ISSUE THREAD

**Issue by zqw961025** [neo4j-contrib/neo4j-apoc-procedures#2063]
I expected the import to include Label and Identity, but unfortunately I didn't see them

**Comment by vga91** [comment]
@zqw961025 
The `apoc.load.csv` simply read the csv, line by line, without performing any write operation (similarly to the [LOAD CSV clause](https://neo4j.com/docs/cypher-manual/current/clauses/load-csv/) )
If you want to create nodes and relations, starting from CSVs, please use the `apoc.import.csv`, which works similarly to the [neo4j admin import tool](https://neo4j.com/docs/operations-manual/current/tutorial/neo4j-admin-import/).

I close the issue for now. If your problem is another, please feel free to open the issue.
