### ISSUE TITLE
Allow to treat JSON numbers as strings

### ISSUE THREAD

**Issue by odessit55** [neo4j-contrib/neo4j-apoc-procedures#2109]
When processing following JSON file:
{"info_file_properties_modified_time":"18446744062065078016",
"info_file_properties_modified_time2":18446744062065078016}
using 
apoc.load.json() 
We get following error:
Failed to invoke procedure `apoc.load.json`: Caused by: com.fasterxml.jackson.core.exc.InputCoercionException: Numeric value (18446744062065078016) out of range of long (-9223372036854775808 - 9223372036854775807)
 at [Source: (apoc.export.util.CountingInputStream); line: 3, column: 59]

Following JSON works fine as I removed a trailing "6" from the string
{"info_file_properties_modified_time":"18446744062065078016",
"info_file_properties_modified_time2":1844674406206507801}

It would be great if we can specify that certain JSON fields should be treated as strings/larger numbers or at least to treat all strings as numbers.

Thank you!

**Comment by voutilad** [comment]
I've been thinking through how to implement this and it I see a few usability concerns. In the above example:

```json
{
  "info_file_properties_modified_time": "18446744062065078016",
  "info_file_properties_modified_time2":18446744062065078016
}
```

How do those values represent time? Is it some number of picoseconds from an epoch? It doesn't appear to be nanoseconds since Unix epoch unless I'm mistaken.

I ask because thinking about this, I don't think having the ability to convert _all_ numbers to `String`s makes sense. It probably makes more of a headache because at some point `String` to `Integer`/`Long`/etc. conversion will need to occur. Providing the ability to do it on a per-field basis is also challenging as JSON can contain nested data, think about:

```json
{
  "map": {
    "aList": [
        { "value": 1 },
        { "value": 1111111111111111111111111111111111111111111}
    ]
  }
}
```

Even if we converted to instances of Java's `BigInteger`, there's no support for them in Neo4j and no way to inspect the type of a property using Cypher (that I know of).

Let's say we convert it instead to Java "String" instances...now you have a value that, again, you can't really inspect in Cypher and conditionally process if it's a valid Java `Number` instance of a `String`. Assuming the value ends up as a `Node` or `Relationship` property, you've got a case of mixed datatypes in the database and the behavior of filtering/sorting/aggregation will most likely be undesired.

For example, if I have nodeswith label `:Node` and a property of `name` with various numeric, `String`, and even temporal data types, then the following Cypher:

```
MATCH (n:Node)
RETURN id(n), n.name
ORDER BY n.name DESC
```

produces:

```
╒═══════╤════════════╕
│"id(n)"│"n.name"    │
╞═══════╪════════════╡
│1      │123         │
├───────┼────────────┤
│3      │0           │
├───────┼────────────┤
│0      │"dave"      │
├───────┼────────────┤
│4      │"0"         │
├───────┼────────────┤
│2      │"2021-07-22"│
└───────┴────────────┘
```

**Comment by voutilad** [comment]
Another argument for why this seems to be a problem with the JSON itself...

If you look at what I'd consider de facto JSON-centric platforms, [jq](https://stedolan.github.io/jq/) and Node, neither can handle the sample provided.

Given:
```
dave@neo-t490s:/tmp$ cat crap.json
{
  "info_file_properties_modified_time": "18446744062065078016",
  "info_file_properties_modified_time2": 18446744062065078016
}
```

`jq` will truncate the precision:

```
dave@neo-t490s:/tmp$ cat crap.json | jq
{
  "info_file_properties_modified_time": "18446744062065078016",
  "info_file_properties_modified_time2": 18446744062065078000
}
```

With Node loading the same file, it does the same:
```
dave@neo-t490s:/tmp$ node -e 'console.log(require("/tmp/crap.json"))'
{
  info_file_properties_modified_time: '18446744062065078016',
  info_file_properties_modified_time2: 18446744062065078000
}
```

So something is amiss here!

On a whim, I took a look at the value in binary in Python:

```
>>> bin(18446744062065078016)
'0b1111111111111111111111111111110101001001111011110110111100000000'
```

Could it just be that the system producing this value goofed and didn't properly mask off the upper 32 bits? If you take the lower 32, that is `0b0101001001111011110110111100000000`, and parse it as a unix timestamp it looks like (to me) potentially the intended timestamp:

```
>>> time.gmtime(int(bin(18446744062065078016)[2:][32:], 2))
time.struct_time(tm_year=2009, tm_mon=4, tm_mday=22, tm_hour=19, tm_min=24, tm_sec=48, tm_wday=2, tm_yday=112, tm_isdst=0)
```
