### ISSUE TITLE
proper termination checks in warmup and graph algorithms

### ISSUE THREAD

**Issue by jexp** [neo4j-contrib/neo4j-apoc-procedures#211]

**Comment by jexp** [comment]
Check here for an example: 
https://github.com/neo4j-contrib/neo4j-apoc-procedures/blob/3.1/src/main/java/apoc/cypher/Cypher.java#L95

**Comment by jexp** [comment]
Create method in Util that wraps this and returns true / false so that we can correctly shut down threads etc. if we have any resources that we hold.

If we don't have any resources we hold open right now, we can also just use txGuard.check();


```
package org.neo4j.procedure;

public interface TerminationGuard {
    void check();
}
```

**Comment by albertodelazzari** [comment]
The object TerminationGuard is available only through the `@Context` annotation. So in the Utils class I did something like that:

`public static boolean transactionIsTerminated(GraphDatabaseAPI db) {
        final KernelTransaction ktx = db.getDependencyResolver()
                                            .resolveDependency(ThreadToStatementContextBridge.class)
                                            .getKernelTransactionBoundToThisThread(true);

        Status reason = ktx.getReasonIfTerminated();
        if (reason != null) {
            return true;
        }

        return false;
    }`

I get the KernelTransaction and if there is a reason for termination than I return true otherwise false

**Comment by jexp** [comment]
yup looks good to me.
