### ISSUE TITLE
Incorrect statistics

### ISSUE THREAD

**Issue by li1191863273** [neo4j-contrib/neo4j-apoc-procedures#2192]
## Guidelines

`Call apoc.meta.stats()`

| labelCount | relTypeCount | propertyKeyCount
| :-: | :-: | :-: |
| 35 |  36 |  70|

Get labelCount: `MATCH (n) RETURN count(distinct labels(n))`
34
34 is the correct number

The real number of propertyKeyCount is 69

## How to Reproduce the Problem

https://neo4j.com/labs/apoc/4.3/export/cypher/#export-cypher-cypher-shell

1. Export Cypher statements from existing Neo4j
```
CALL apoc.export.cypher.all("all.cypher", {
    format: "cypher-shell",
    useOptimizations: {type: "UNWIND_BATCH", unwindBatchSize: 20}
})
YIELD file, batches, source, format, nodes, relationships, properties, time, rows, batchSize
RETURN file, batches, source, format, nodes, relationships, properties, time, rows, batchSize;
```

2. Recreate a new Neo4j container, and then run the Cypher statement obtained in the previous step

```
cat all.cypher | ./bin/cypher-shell -a <bolt-url> -u neo4j -p <password> --format verbose
```

3. Restart the container, run the statistical statement `Call apoc.meta.stats()`, and find that the statistical data is incorrect

### Versions
  - OS: CentOS Linux 7 (Core) x86_64
  - Neo4j-docker: neo4j:4.3.3
  - Neo4j-Apoc: apoc-4.3.0.0-all.jar

**Comment by vga91** [comment]
@li1191863273 
I think that the `labelCount` problem should be fixed with #2097, which has been merged for 4.2, but not yet for 4.3.

Regarding the `propertyKeyCount`, it is an internal problem in neo4j, in fact the same problem also occurs with the `CALL db.propertyKeys()` which is used by the `apoc.meta.stats` (it is explained here: https://neo4j.com/developer/kb/why-do-my-deleted-property-keys-appear/).
This happens because during the export, a `UNIQUE IMPORT ID` property and a `UNIQUE IMPORT LABEL` label are created, which are deleted at the end of the script, but the property remains in the count.

To be sure, can you try using the jar I attached (with the above fix) to verify that the `labelCount` remains 34?

[apoc-4.3.0.0-all.jar.zip](https://github.com/neo4j-contrib/neo4j-apoc-procedures/files/7099975/apoc-4.3.0.0-all.jar.zip)

**Comment by li1191863273** [comment]
Thank you very much, labelCount is correct

**Comment by li1191863273** [comment]
But `propertyKeyCount` is still 70 instead of 69
