### ISSUE TITLE
Deleting nodes when having an `apoc.trigger` registered returns `Neo.DatabaseError.Transaction.TransactionCommitFailed`

### ISSUE THREAD

**Issue by process0** [neo4j-contrib/neo4j-apoc-procedures#2247]
# Problem

Using triggers,  `CALL apoc.trigger.add('test', "CALL apoc.log.info('OK') RETURN 1", { phase: 'afterAsync' });` will fail when deleting nodes (e.g `MATCH (n:Something) DELETE n`)  with `Neo.DatabaseError.Transaction.TransactionCommitFailed`.

## Expected Behavior (Mandatory)

Should not get `Neo.DatabaseError.Transaction.TransactionCommitFailed`

## Actual Behavior (Mandatory)

Running a `DELETE` query when a trigger setup returned `Neo.DatabaseError.Transaction.TransactionCommitFailed`.

## How to Reproduce the Problem

Using triggers,  `CALL apoc.trigger.add('test', "CALL apoc.log.info('OK') RETURN 1", { phase: 'afterAsync' });` will fail when deleting nodes (e.g `MATCH (n:Something) DELETE n`)  with `Neo.DatabaseError.Transaction.TransactionCommitFailed`.

### Simple Dataset (where it's possibile)

Using triggers,  `CALL apoc.trigger.add('test', "CALL apoc.log.info('OK') RETURN 1", { phase: 'afterAsync' });` will fail when deleting nodes (e.g `MATCH (n:Something) DELETE n`)  with `Neo.DatabaseError.Transaction.TransactionCommitFailed`.

### Steps (Mandatory)

Using triggers,  `CALL apoc.trigger.add('test', "CALL apoc.log.info('OK') RETURN 1", { phase: 'afterAsync' });` will fail when deleting nodes (e.g `MATCH (n:Something) DELETE n`)  with `Neo.DatabaseError.Transaction.TransactionCommitFailed`.

## Specifications (Mandatory)

Currently used versions

### Versions

  - OS: Ubuntu 20.04.3 LTS
  - Neo4j: neo4j-enterprise 4.3.6  
  - Neo4j-Apoc: apoc-4.3.0.0-all.jar

**Comment by klongmitre** [comment]
I'm also seeing this. Have you made any progress on this? Found a work around?

**Comment by magaton** [comment]
I am seeing a similar problem but with deleted relationship.
https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/1450#issuecomment-1015771166

**Comment by jexp** [comment]
Did you try a more recent apoc version than 4.3.0.0 ?

**Comment by jexp** [comment]
Yep, sorry it's a bug, it tries to bind the node again to make it available which is of course not possible as the tx is already closed and the node is gone.

```
Caused by: org.neo4j.graphdb.NotInTransactionException: This transaction has already been closed.
        at org.neo4j.kernel.impl.api.KernelTransactionImplementation.assertTransactionOpen(KernelTransactionImplementation.java:676) ~[neo4j-kernel-4.4.0.jar:4.4.0]
        at org.neo4j.kernel.impl.api.KernelTransactionImplementation.assertOpen(KernelTransactionImplementation.java:688) ~[neo4j-kernel-4.4.0.jar:4.4.0]
        at org.neo4j.kernel.impl.newapi.Read.singleNode(Read.java:353) ~[neo4j-kernel-4.4.0.jar:4.4.0]
        at org.neo4j.kernel.impl.core.NodeEntity.singleNode(NodeEntity.java:787) ~[neo4j-kernel-4.4.0.jar:4.4.0]
        at org.neo4j.kernel.impl.core.NodeEntity.getLabels(NodeEntity.java:620) ~[neo4j-kernel-4.4.0.jar:4.4.0]
        at org.neo4j.kernel.impl.core.NodeEntity.getLabels(NodeEntity.java:612) ~[neo4j-kernel-4.4.0.jar:4.4.0]
        at apoc.trigger.TriggerMetadata.lambda$rebindDeleted$0(TriggerMetadata.java:98) ~[apoc-4.4.0.1-all.jar:4.4.0.1]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[?:?]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
        at apoc.trigger.TriggerMetadata.rebindDeleted(TriggerMetadata.java:105) ~[apoc-4.4.0.1-all.jar:4.4.0.1]
        at apoc.trigger.TriggerMetadata.from(TriggerMetadata.java:80) ~[apoc-4.4.0.1-all.jar:4.4.0.1]
        at apoc.trigger.TriggerHandler.afterAsync(TriggerHandler.java:205) ~[apoc-4.4.0.1-all.jar:4.4.0.1]
        at apoc.trigger.TriggerHandler.afterCommit(TriggerHandler.java:200) ~[apoc-4.4.0.1-all.jar:4.4.0.1]
        at apoc.trigger.TriggerHandler.afterCommit(TriggerHandler.java:34) ~[apoc-4.4.0.1-all.jar:4.4.0.1]
```

**Comment by klongmitre** [comment]
@jexp - Thanks for looking into this. Is this an easy bug to fix? Can it be provided in a patch release sometime soon?

**Comment by klongmitre** [comment]
@jexp / @conker84  - any update on this? I'm noticing that writes made to a node (e.g. `SET node.field = "foo"`) aren't applied when done in a trigger that executes in the `before` stage when the trigger is due to a node deletion. I'm guessing it's because of the `TransactionError` being thrown.

**Comment by vga91** [comment]
@klongmitre @process0 

[apoc-4.4.0.3-all.jar.zip](https://github.com/neo4j-contrib/neo4j-apoc-procedures/files/8131148/apoc-4.4.0.3-all.jar.zip)


I attached a `.jar` with some changes which should fix the problem.
Could you try your triggers with this one?

Please note that the `afterAsync` implementation is unchanged,
instead with `after` and `before` I added 2 procedures, `apoc.trigger.rebuildRelationship` and `apoc.trigger.rebuildNode` to 
rebuild a node/relationship as a virtual entity (so, it should be used [this functions](https://neo4j.com/labs/apoc/4.1/virtual/virtual-nodes-rels/) instead of "classic" cypher functions )

That is, for example
```
CALL apoc.trigger.add('myTrigger', 
"UNWIND $deletedRelationships as deletedRel 
WITH apoc.trigger.rebuildRelationship(deletedRel, $removedRelationshipProperties) AS deletedRel 
CREATE (r:Report {id: id(deletedRel), type: apoc.rel.type(deletedRel)}) 
WITH r, deletedRelset r+=apoc.any.properties(deletedRel)" ,
{phase:'before'})
```

**Comment by JMHReif** [comment]
@klongmitre, I apologize for the delay. There was a backlog of issues and pull requests I have been wading through. The pull request to fix this issue has been created, reviewed, and merged. It should be in the next release of APOC 4.3!

**Comment by mondbond** [comment]
Hello @conker84, @JMHReif.  As I understand, this fix is not released for now. Please, can you share information when it will be released ?

**Comment by process0** [comment]
Late to test. These releases fix this issue. Thanks!

**Comment by srnnukala** [comment]
I have a similar issue for which I opened an issue 
(https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/3216)

Expected Behavior (Mandatory)
Delete nodes and relationships while having apoc.trigger.propertiesByKey($removedNodeProperties,"progenitorId")

Sample apoc trigger in production :

CALL apoc.trigger.add('requiredIdentifiers_removedNodeProperties_preventRemovalOnProgenitorId',
'UNWIND apoc.trigger.propertiesByKey($removedNodeProperties,"progenitorId") AS prop WITH prop.node AS n, prop.old
AS oldValue SET n.progenitorId=oldValue RETURN 0', {phase:'before'});
CALL apoc.trigger.add('requiredIdentifiers_removedRelationshipProperties_preventRemovalOnExternalId',
'UNWIND apoc.trigger.propertiesByKey($removedRelationshipProperties,"externalId") AS prop WITH prop.relationship AS r,
prop.old AS oldValue SET r.externalId=oldValue RETURN 0', {phase:'before'});
Actual Behavior (Mandatory)
Neo.ClientError.Transaction.TransactionHookFailed: Error executing trigger requiredIdentifiers_removedNodeProperties_preventRemovalOnProgenitorId in phase before
org.neo4j.graphdb.TransactionFailureException: Unable to complete transaction.

How to Reproduce the Problem
-> CREATE DATABASE dummy
-> CALL apoc.trigger.add('requiredIdentifiers_removedNodeProperties_preventRemovalOnProgenitorId',
'UNWIND apoc.trigger.propertiesByKey($removedNodeProperties,"progenitorId") AS prop WITH prop.node AS n, prop.old AS oldValue
SET n.progenitorId=oldValue RETURN 0',
{phase:'before'});
-> CREATE (node:dummyActivity {progenitorId : 123456})
-> MATCH (n:Activity) where n.progenitorId = 123456 delete n

@conker84 - can you please look into this when you get time?
I am using ( Neo4j: 4.4.8, Neo4j-Apoc: 4.4.0.4 )
Background:
With apoc.triggers in place, we don't allow users to delete/update the node properties or relationship properties, however we give them access delete nodes and relationship and are successful using neo4j 3.5.18 and apoc 3.5.0.12-all.

**Comment by vga91** [comment]
@srnnukala See https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/3216#issuecomment-1275932742
