### ISSUE TITLE
apoc.meta.relTypeProperties returns nothing when the Relationship type contains '_'

### ISSUE THREAD

**Issue by OBoussekey** [neo4j-contrib/neo4j-apoc-procedures#2383]
## Guidelines

Please note that GitHub issues are only meant for bug reports/feature requests. If you have questions on how to use APOC, please ask on [the Neo4j Discussion Forum](https://community.neo4j.com/c/neo4j-graph-platform/procedures-apoc) instead of creating an issue here.

## Expected Behavior (Mandatory)
CALL apoc.meta.relTypeProperties({includeRels: ['SEND_TO']}) should return relationship properties

## Actual Behavior (Mandatory)
No properties are returned when the relationship name contains '_'

## How to Reproduce the Problem
Call the apoc.meta.relTypeProperties with a relationship type containing an underscore character ('_')

### Simple Dataset (where it's possibile)

```
//Insert here a set of Cypher statements that helps us to reproduce the problem

```

### Steps (Mandatory)

  1. CALL apoc.meta.relTypeProperties({includeRels: ['SENDTO']})  will return something (if SENDTO relationship has properties of course)
  2. CALL apoc.meta.relTypeProperties({includeRels: ['SEND_TO']}) will return nothing, even if SEND_TO relationship has properties

## Specifications (Mandatory)

Currently used versions

### Versions

  - OS: Aura Free
  - Neo4j: Aura free
  - Neo4j-Apoc: Aura Free

**Comment by vga91** [comment]
@OBoussekey 

Can you provide the specific APOC version? Just type `RETURN apoc.version()`.

I tried with both apoc `4.4.0.0` and `4.3.0.4`, creating a simple dataset 
```
CREATE (:Node)-[:SEND_TO {a: 1}]->(:Node)
```
and the `CALL apoc.meta.relTypeProperties({includeRels: ['SEND_TO']})` 
returns correctly a row with `propertyName` = `"a"`.

**Comment by OBoussekey** [comment]
Hi,

Thanks for your reply.
I'm using an Aura database (free) with runs apoc 4.4.0.0 and a desktop
version with apoc 4.2.0.0 but unfortunately, I have the same results with
both versions

With the Aura database, here are the results I have :
[image: image.png]

and APOC function returns :
[image: image.png]

Regards,

Olivier BOUSSEKEY
Consultant & Fondateur
+33 6 17 33 99 12
http://www.opb-consulting.fr


Le lun. 13 déc. 2021 à 12:41, Giuseppe Villani ***@***.***> a
écrit :

**Comment by OBoussekey** [comment]
Here are the images attached

Olivier BOUSSEKEY
Consultant & Fondateur
+33 6 17 33 99 12
http://www.opb-consulting.fr


Le jeu. 16 déc. 2021 à 13:10, Giuseppe Villani ***@***.***> a
écrit :

**Comment by vga91** [comment]
@OBoussekey 

Mmh, it seems that with emails images get lost somewhere...
Please, can you attach them directly here into GitHub thread?
Or even better, if you can, can you provide a simple dataset to replicate the issue?

**Comment by OBoussekey** [comment]
@vga91 
Here are the images :
![image](https://user-images.githubusercontent.com/81627207/147147020-55b3aafc-fa51-422b-bde5-f815c49a7ccc.png)

![image](https://user-images.githubusercontent.com/81627207/147147056-689aa9f5-7cbb-4e8a-9cbd-2a1d59b0d895.png)

**Comment by lavkan** [comment]
Is there an update on this issue? I tried to write a query and later realized that unless the label types of the end nodes of the relationships is available, the query will not be fast. So maybe some timeout exception is raised to honor it an empty table is outputted?

**Comment by vga91** [comment]
@OBoussekey @lavkan 

I linked a pull request with a bugfix which I thought should fix the problem.
That is, with nodes with double relationships, i.e. `CREATE (a:A)-[:FIRST_A {a: 1}]->(b:B), (a)-[:SECOND {b: '2'}]->(c)`, 
the query `CALL apoc.meta.relTypeProperties({includeRels: ['FIRST_A']})` returned nothing

But the last answer made me think that your problem is probably something else.

For example, given this dataset, with 200 relationships without properties and 1 rel with properties:

```
UNWIND range (0, 200) as idx CREATE (a: A)-[:FIRST_A]-> (b: B)
CREATE (a: A) - [: FIRST_A {a: 1}] -> (b: B)
```

if I do:
```
CALL apoc.meta.relTypeProperties ({includeRels: ['FIRST_A']})
```
the result have `propertyName` and `propertyTypes` columns `null`.

On the other hand, if I set the `maxRels` property, the result is the correct one:
``
CALL apoc.meta.relTypeProperties ({includeRels: ['FIRST_A'], maxRels: 1000})
``
this is because the procedure analyzes (by default) only the first 100 relations it finds, which in this case have no properties.

Is this your use case?

Otherwise, can you try this jar with the above fix?

[apoc-4.3.0.4-all.jar.zip](https://github.com/neo4j-contrib/neo4j-apoc-procedures/files/8131900/apoc-4.3.0.4-all.jar.zip)
