### ISSUE TITLE
apoc.data.domain not working properly for emails

### ISSUE THREAD

**Issue by tomasonjo** [neo4j-contrib/neo4j-apoc-procedures#250]
`return apoc.data.domain("foo.bar@foobar.com")` returns foo.bar

seems like the pattern is that when there is a dot on left side of @ function messes up

**Comment by InverseFalcon** [comment]
I can take this one, should be fairly easy, we can just iterate over the split tokens in reverse if we detect an @ sign.

Note though that this may give bad results for URLs with "@" in the query string, so that should probably be avoided by filtering out before the function call, if possible. The most robust solution if needed later on would be splitting this into two separate functions.
