### ISSUE TITLE
apoc.load.xml on large file generates OoM Errors

### ISSUE THREAD

**Issue by sirReeall** [neo4j-contrib/neo4j-apoc-procedures#2723]
## Feature description 
apoc.load.xml should be able to stream during loading of large xml files.

Currently a relatively small xml of 1GB can generate OoM heap errors even when used with a simple cypher statement. For example:

```
call apoc.load.xml("file:///var/lib/neo4j/import/small.xml") 
             yield value as releases
             unwind releases._children as release
             with release.id as releaseID,
               [item in release._children where item._type = "title"][0] as title
             MERGE (r:Release {id: releaseID})
             SET r.title = title._text;
```

Discussed with @jexp over slack. This is in contrast to `apoc.import.xml(file,config)` which does stream.

**Comment by jexp** [comment]
our comments from slack

you could try to use xpath instead then it should stream
 about the iterate one you should do the unwind releases._children in the source statement. otherwise you pass the complete xml json object to the next query if this xml is a single xml structure…

 hmm odd, I was sure that load.xml streams but it doesn't seem so
  sorry for that
 only apoc.import.xml(file,config) seems to stream
[21h](https://neo4j.slack.com/archives/C136J23GE/p1649333981882219?thread_ts=1649329476.814319&cid=C136J23GE)
https://github.com/neo4j-contrib/neo4j-apoc-procedures/blob/e5abd54f2ef325d3e9eef6c9e90e3089503cfa77/core/src/main/java/apoc/load/Xml.java#L115-L156

```
    private Stream<MapResult> parse(InputStream data, boolean simpleMode, String path, boolean failOnError) throws Exception {
        List<MapResult> result = new ArrayList<>();
        try {
            DocumentBuilderFactory documentBuilderFactory = DocumentBuilderFactory.newInstance();
            documentBuilderFactory.setNamespaceAware(true);
```

we should change that, esp. with xpath to operate on a stream similar to import.xml
