### ISSUE TITLE
Feature Request: Additional collection functions - shuffle(), randomItems()

### ISSUE THREAD

**Issue by InverseFalcon** [neo4j-contrib/neo4j-apoc-procedures#277]
This requests some additional collection helper functions:

- shuffle() - shuffles the elements of a given collection
- randomItem() - returns a random element from the given collection
- randomItems() - given an integer n, returns a collection of n random elements from the original collection. "removeOnPick" boolean parameter determines if a selection removes it from the list (makes it not available for picking again) or leaves the list alone (so the same item may be randomly picked again.

**Comment by jexp** [comment]
In Neo4j 3.2. there is `reverse` for collections.

The other ones are good ideas, also good starting point for a pull request as those are 1:1 mappings to `java.util.Collections.*` helper functions.

For randomItems it probably makes more sense to have two functions instead of a boolean parameter, although as we have default values now it could just default to removeOnPick=true.

**Comment by InverseFalcon** [comment]
I think I may be missing something, how do defaults work between apoc procedure calls and their paired methods?

**Comment by jexp** [comment]
Since Neo4j 3.1 you can provide a defaultValue attribute on the @Name annotation both for functions and procedures. There are a few examples in the 3.1 branch

**Comment by InverseFalcon** [comment]
Per the recommendation on slack, I was targeting the 3.0 branch. Is it recommended to target 3.1 at this time instead? Or is it good enough to go for 3.0, and then make the boolean have a default value on 3.1, once it gets there?

**Comment by InverseFalcon** [comment]
Feature request fulfilled with merge of issue #296, this is on the 3.1 branch.
