### ISSUE TITLE
`NoSuchMethodError` exception for `getReadCapabilities` when trying to use `apoc.convert.fromJsonList`

### ISSUE THREAD

**Issue by tekrei** [neo4j-contrib/neo4j-apoc-procedures#2861]
I am receiving `NoSuchMethodError` for `com.fasterxml.jackson.core.JsonParser.getReadCapabilities()` when I try to use `apoc.convert.fromJsonList`.

## Expected Behavior (Mandatory)

Query should return nodes.

## Actual Behavior (Mandatory)

It is giving the following error:

```
Failed to invoke function `apoc.convert.fromJsonList`: Caused by: java.lang.NoSuchMethodError: 'com.fasterxml.jackson.core.util.JacksonFeatureSet com.fasterxml.jackson.core.JsonParser.getReadCapabilities()'
```

## How to Reproduce the Problem

The following simple apoc.convert.fromJsonList giving the error:

`RETURN apoc.convert.fromJsonList("[{'token': '1', 'scope': 'test'},{'token': '2','scope': 'test'}]") AS data`

### Steps (Mandatory)

1. Just run the given query.

## Screenshots (where it's possible)

<img width="600" alt="error" src="https://user-images.githubusercontent.com/200193/167118314-aee5fc86-8820-497b-8a3f-ba7063f10134.png">

## Specifications (Mandatory)

Currently used versions

### Versions

  - OS: Neo4j is deployed as a Docker container using neo4j:latest image over Ubuntu 22.04 host
  - Neo4j: 4.4.6
  - Neo4j-Apoc: 4.4.0.4

**Comment by tekrei** [comment]
Hello again,

We had to revert back to Neo4j 4.4.1, which is using APOC 4.4.0.3, to make the query work as expected without errors.

![image](https://user-images.githubusercontent.com/200193/167366311-697da2c8-b7ad-4b36-8d3b-707fc0e7e5e7.png)

**Comment by vga91** [comment]
@tekrei 
I just tried the procedure using the same apoc/neo4j docker version as yours, and it works for me.
Did you install any other plugins, besides the apoc?
Also, there is something else in docker logs?

**Comment by tekrei** [comment]
Hello,

Here is the command I am using for running the container:

```
docker run -d --restart unless-stopped --name neo4j \
    -e NEO4J_AUTH=neo4j/test \
    -e NEO4J_dbms_default__listen__address=0.0.0.0 \
    -e NEO4J_dbms_default__advertised__address=localhost \
    -e NEO4J_dbms_connector_bolt_advertised__address=:7687 \
    -e NEO4J_dbms_connector_http_advertised__address=:7474 \
    -e NEO4JLABS_PLUGINS='["apoc", "graph-data-science", "n10s"]' \
    -e NEO4J_dbms_unmanaged__extension__classes=n10s.endpoint=/rdf \
    -e NEO4J_apoc_export_file_enabled=true \
    -e NEO4J_apoc_import_file_enabled=true \
    -e NEO4J_apoc_import_file_use__neo4j__config=false \
    -e apoc.http.timeout.connect=0  \
    -e apoc.http.timeout.read=0  \
    --health-cmd "wget --no-verbose --tries=1 --spider http://localhost:7474 || exit 1" \
    --health-interval=120s --health-timeout=30s \
    -p 7474:7474 -p 7687:7687 neo4j:latest
```

And here is the logs after running the query:

```
Changed password for user 'neo4j'.
Fetching versions.json for Plugin 'apoc' from https://neo4j-contrib.github.io/neo4j-apoc-procedures/versions.json
Installing Plugin 'apoc' from https://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/download/4.4.0.4/apoc-4.4.0.4-all.jar to /var/lib/neo4j/plugins/apoc.jar 
Applying default values for plugin apoc to neo4j.conf
Fetching versions.json for Plugin 'graph-data-science' from https://graphdatascience.ninja/versions.json
Installing Plugin 'graph-data-science' from https://graphdatascience.ninja/neo4j-graph-data-science-2.0.3.jar to /var/lib/neo4j/plugins/graph-data-science.jar 
Applying default values for plugin graph-data-science to neo4j.conf
Fetching versions.json for Plugin 'n10s' from https://neo4j-labs.github.io/neosemantics/versions.json
Installing Plugin 'n10s' from https://github.com/neo4j-labs/neosemantics/releases/download/4.4.0.1/neosemantics-4.4.0.1.jar to /var/lib/neo4j/plugins/n10s.jar 
Applying default values for plugin n10s to neo4j.conf
2022-05-09 14:16:16.175+0000 INFO  Starting...
2022-05-09 14:16:17.273+0000 INFO  This instance is ServerId{e8edef7f} (e8edef7f-5efa-4bb6-b3a8-2397a7e46622)
2022-05-09 14:16:20.113+0000 INFO  ======== Neo4j 4.4.6 ========
2022-05-09 14:17:03.820+0000 INFO  Initializing system graph model for component 'security-users' with version -1 and status UNINITIALIZED
2022-05-09 14:17:03.846+0000 INFO  Setting up initial user from `auth.ini` file: neo4j
2022-05-09 14:17:03.847+0000 INFO  Creating new user 'neo4j' (passwordChangeRequired=false, suspended=false)
2022-05-09 14:17:03.877+0000 INFO  Setting version for 'security-users' to 3
2022-05-09 14:17:03.884+0000 INFO  After initialization of system graph model component 'security-users' have version 3 and status CURRENT
2022-05-09 14:17:03.891+0000 INFO  Performing postInitialization step for component 'security-users' with version 3 and status CURRENT
2022-05-09 14:17:09.304+0000 INFO  Called db.clearQueryCaches(): Query cache already empty.
2022-05-09 14:17:09.671+0000 INFO  Bolt enabled on 0.0.0.0:7687.
2022-05-09 14:17:09.732+0000 INFO  Mounted unmanaged extension [n10s.endpoint] at [/rdf]
2022-05-09 14:17:13.491+0000 INFO  Remote interface available at http://localhost:7474/
2022-05-09 14:17:13.496+0000 INFO  id: A5EC82EC47AA278F58217020318FB4A3B7AF1F4A0DABE2F30704C0D07C58A86B
2022-05-09 14:17:13.497+0000 INFO  name: system
2022-05-09 14:17:13.497+0000 INFO  creationDate: 2022-05-09T14:16:22.277Z
2022-05-09 14:17:13.497+0000 INFO  Started.
```

**Comment by vga91** [comment]
[Here](https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/2670) we exclude the `jackson-databind` from the dependencies to pick the Neo4j one.
So currently the compiled jar doesn't contains the `databind` dependency.
I think the problem is on `n10s` side which has some kind of conflict.
After some tests I found [this hint](https://stackoverflow.com/questions/27746750/exception-in-thread-main-java-lang-nosuchmethoderror-com-fasterxml-jackson-co),
and, indeed, by adding the `jackson-core` 2.9.10 dependency, the procedure works.

**Comment by egermani** [comment]
Just wanted to mention that I saw an identical error when I invoked `apoc.gephi.add`. Error message was:

`Failed to invoke function `apoc.gephi.add`: Caused by: java.lang.NoSuchMethodError: 'com.fasterxml.jackson.core.util.JacksonFeatureSet com.fasterxml.jackson.core.JsonParser.getReadCapabilities()'`

I was able to solve it by uninstalling the neosemantics plugin. Thank you for troubleshooting this, @vga91!

**Comment by nissimsan** [comment]
@vga91, I'm facing this exact issue too, attempting to follow [this tutorial](https://github.com/transmute-industries/verifiable-data/tree/main/packages/cli/src/commands/neo4j). 
I need both `neosemantics` and `apoc` (for json-ld). Is there a way to make that work? If yes, would you mind spelling out what I need to do, pls?

**Comment by stugorf** [comment]
I can add that Neo4j 4.4.10 with APOC 4.4.0.8 results in apoc.load.json not working. n10s is installed in /plugins/

Are there any updates on this issue?

**Comment by vga91** [comment]
@nissimsan @stugorf 

At the moment, as a workaround, we can change the `n10s` plugin in order not to cause conflicts with` apoc`.
That is:
- execute in terminal `git clone https://github.com/neo4j-labs/neosemantics.git`
- execute `cd neosemantics`
- execute `git checkout <VERSION>`, considering that the first two version numbers between `Neo4j` and n10s `<VERSION>` branch have to match, for example with neo4j `4.3.3` we have to execute `git checkout 4.3`,  with neo4j `4.2.12` we have to execute `git checkout 4.2`, etc...
- add in the file `pom.xml` the following dependency (note that the version in `2.9.10` because currently the `jackson-databind` version is `2.9.10.4`, in the future the version of jackson-databind could change, and therefore the `jackson-core` version)
```
    <dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-core</artifactId>
      <version>2.9.10</version>
      <scope>provided</scope>
    </dependency>
```
- execute `mvn clean install -DskipTests`
- copy the `<neosemantics_path>/target/neosemantics-<version>.jar` file in the `$NEO4J_HOME/plugins` folder, taking care to delete, if present, the file `n10s-<version>.jar`
