### ISSUE TITLE
apoc.custom.declareFunction does not work with APOC 4.4.0.4

### ISSUE THREAD

**Issue by jkolster** [neo4j-contrib/neo4j-apoc-procedures#2880]
I have the following issue with APOC 4.4.0.4

When running the following example code (https://neo4j.com/labs/apoc/4.2/overview/apoc.custom/apoc.custom.declareFunction/#usage-apoc.custom.declareFunction) using the latest APOC 4.4.0.4 library:

CALL apoc.custom.declareFunction(
  'double(input::INT) :: INT',
  'RETURN $input*2 as answer'
);

I expect the function 'double' to be created without issues. 

But when I run this statement I get the following error:

Neo.ClientError.Procedure.ProcedureCallFailed
Failed to invoke procedure `apoc.custom.declareFunction`: Caused by: org.neo4j.exceptions.SyntaxException: Type mismatch for parameter 'input': expected Float, Integer or Duration but was String (line 1, column 16 (offset: 15))
"EXPLAIN RETURN $input*2 as answer"

This issue does NOT occur when using APOC version 4.4.0.3!!! 
Could you please fix this issue?

Versions used

  - OS: MacOS 12.3.1
  - Neo4j: 4.4.5
  - Neo4j-Apoc: 4.4.0.4

**Comment by vga91** [comment]
@jkolster 
The bug is solved through this pr https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/2702,
which has yet to be merged and released in 4.4.

While waiting for the release (and to be sure this works for you too), can you try with this attached zipped-jar?

[apoc-4.4.0.5-all.jar.zip](https://github.com/neo4j-contrib/neo4j-apoc-procedures/files/8678913/apoc-4.4.0.5-all.jar.zip)
