### ISSUE TITLE
Procedure apoc.config.list missing in 5.1

### ISSUE THREAD

**Issue by wadael** [neo4j-contrib/neo4j-apoc-procedures#3276]
## Expected Behavior (Mandatory)
returns KV pairs of java properties
online doc is present at https://neo4j.com/labs/apoc/5/overview/apoc.config/apoc.config.list/
so this is not a deprecated procedure 

## Actual Behavior (Mandatory)
Procedure reported missing

## How to Reproduce the Problem
execute  CALL apoc.config.list()

### Steps (Mandatory)

  1. open neo browser
  1. execute   CALL apoc.config.list()
  1.notice the error message

## Specifications (Mandatory)

Currently used versions

### Versions

  - OS: linux 6.0.1
  - Neo4j: 5.1
  - Neo4j-Apoc: 5.1

**Comment by nadja-muller** [comment]
Hi.
We made the decision for Neo4j 5 to split the existing apoc into two parts, apoc core and apoc extended.
The procedure you are looking for is a procedure in apoc extended, and therefore not in Neo4j-Apoc (core): 5.1. We've recently released  apoc extended for 5.1, see https://github.com/neo4j-contrib/neo4j-apoc-procedures/releases. You can use the procedure by adding the apoc extended plugin. Please note that apoc extended is a lab project and is not supported by neo4j. Many procedures have been excluded because they do not meet the security standard we want to provide in neo4j.

**Comment by vga91** [comment]
As Nadja said, since version 5.x there are 2 different jars. To use the `apoc.config.list` (which is labeled an `Apoc Extended`) we have to download the Extended jar from here: https://github.com/neo4j-contrib/neo4j-apoc-procedures/releases.

I'm closing the issue for now,  feel free to reopen in case you still have problems.
