### ISSUE TITLE
add optional treshold to similarity functions to limit the number of values returned

### ISSUE THREAD

**Issue by jexp** [neo4j-contrib/neo4j-apoc-procedures#336]
@InverseFalcon 
the value should probably default to 0 or some reasonable percentage?

/cc @maxdemarzi

**Comment by maxdemarzi** [comment]
Also minimum... If you rated 300 movies and I rated 5, but my 5 ratings are same as yours, are we really 100% similar.

**Comment by InverseFalcon** [comment]
@maxdemarzi At the moment the functions take in two vectors, and it's up to the caller to populate them and pass in vectors which make sense in their use case, using COALESCE where necessary. The vectors must be the same size, and since COLLECT() excludes null values, you wouldn't be able to accidentally pass in a 300-length list and a 5-length list. I think the only way for a bad kind of calculation to occur would be if the user matched only to nodes in common.

@jexp The functions should only return a single Double similarity. I don't think there's anything to limit, or rather, the limiting should be done before the similarity call since it's one call per row.

**Comment by jexp** [comment]
The idea is to limit / filter on the similarity score, of course one can post-filter but it would be nice to do that internally.

In general for 3.2. we might look into making this an aggregation function?

**Comment by vga91** [comment]
Closing as the `algo.cosineSimilarity` and `algo.euclideanSimilarity` are no longer available in 4.1+
