### ISSUE TITLE
why 5.22.0 release assets has not "apoc-5.22.0-all.jar" ? which file should I download?

### ISSUE THREAD

**Issue by tangwenixng** [neo4j-contrib/neo4j-apoc-procedures#4165]
why 5.22.0 release assets has not "apoc-5.22.0-all.jar" ? which file should I download?

**Comment by Lojjs** [comment]
Hi @tangwenixng. Since 5.0, APOC core and extended are released separately and the code is placed in separate repositories on Github.

For APOC core, apoc-5.22.0-core.jar can be downloaded [in the new repository](https://github.com/neo4j/apoc/releases/tag/5.22.0)
For APOC extended, apoc-5.22.0-extended.jar can be downloaded [in this repository](https://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/tag/5.22.0)
