### ISSUE TITLE
apoc.import.graphml issue - export using same APOC library

### ISSUE THREAD

**Issue by giribabuvenugopal** [neo4j-contrib/neo4j-apoc-procedures#438]
i am getting following error

graphml size is 26 gb

neo4j> CALL apoc.import.graphml("/backup/ex_mus_graphml",{batchsize:10000, readLabels: true, storeNodeIds: false, defaultRelationshipType:"RELATED"});
Failed to invoke procedure `apoc.import.graphml`: Caused by: java.lang.RuntimeException: Error executing in separate thread: javax.xml.stream.XMLStreamException: ParseError at [row,col]:[13972763,232]
Message: An invalid XML character (Unicode: 0x7) was found in the element content of the document.
neo4j>

**Comment by jexp** [comment]
Did you check that position ?

**Comment by giribabuvenugopal** [comment]
i was when look into query line i dont see it. anything

**Comment by WyrdNexus** [comment]
I just encountered the exact same issue. Unicode char was in source data, which was imported using `apoc.load.json`

One node has a string property containing `"1628\u001e–30"`.

Note: tracking this down is much easier with an editor which will display unusual characters. 

In this instance, GraphML export _should not_ allow those characters through without either removing them, or encoding them. 

**Heading:** `<?xml version="1.0" encoding="UTF-8"?>` should not allow for any non-utf-8 characters, though solving that problem is no easy task.

Editing the file created by `apoc.export.graphml.all('file',{})` revealed unicode characters displayed as `<0x1e>`. 

Fixing the file:
1. Regex find and replace:
    * Find: `[\x{07}\x{1e}\x{1f}]`
    * ReplaceWith: ` `
2. Save with encoding: `UTF-8`

Following those corrective steps, the import ran cleanly.

**Comment by vga91** [comment]
Related to #1283
