### ISSUE TITLE
 two "CALL/CREATE" will take forever to execute 

### ISSUE THREAD

**Issue by jiminjia** [neo4j-contrib/neo4j-apoc-procedures#499]
jiminjia [4:19 PM] 
If I put two "CALL/CREATE" together like below,  the execution will take forever and never complete.  However,  If I execute each "CALL/CREATE" separately,  they completed immediately.  Is this expected ?    

CALL apoc.mongodb.get('mongodb://localhost:27017', 'local', 'collection1', null) YIELD value AS coll1_v
CREATE (node1:Node1{_id: coll1_v.id})

CALL apoc.mongodb.get('mongodb://localhost:27017', 'local', 'collection2', null) YIELD value AS coll2_v
CREATE (node2:Node2{_id: coll2_v.id})

**Comment by InverseFalcon** [comment]
Which version of Neo4j are you using? As far as I know the example query you gave should give a syntax error, you need a WITH between CREATE and CALL.

More than that, even with a very basic WITH, you're increasing the number of rows here. So if the first block yields 500 rows of `coll1_v` values, and you don't decrease the cardinality, the next CALL statement will be made for each of those 500 rows instead of a single time, and the YIELD will perform a cross product with `coll1_v`, resulting in the creation of duplicate :Node2 nodes.

You may want to read this knowledge base article on [resetting query cardinality](https://neo4j.com/developer/kb/resetting-query-cardinality/).

**Comment by InverseFalcon** [comment]
I believe this issue is pretty much solved, as it seems to be an issue about understanding and resetting row cardinality.
