### ISSUE TITLE
Unsupported return type <java.util.stream.Stream<java.lang.Long>> of function defined

### ISSUE THREAD

**Issue by ontologiae** [neo4j-contrib/neo4j-apoc-procedures#573]
Hi, I'm trying to add a function in nodes.java that create dynamic relationships from a CSV file, and the compiler doesn't accept it

Here' the function signature
```java
  @Procedure(mode = Mode.WRITE)
  @UserFunction("apoc.nodes.loadCsvRelationships")
  @Description("apoc.nodes.loadCsvRelationships( path, key )")
  public int loadCsvRelationships(@Name("path") final String csvPath, @Name("key") final String idxKey ) {
     //..
   return an_int;
  }
```
I get a error : `Return type of Nodes#loadCsvRelationships must be java.util.stream.Stream`
Which is strange because there's function which doesn't return a Stream in the same file  (apoc.nodes.connected for instance)

If I modify it with 
```java
public Stream<Long> loadDatabase(@Name("path") final String csvPath, @Name("key") final String idxKey ) {
```

I get : `neo4j-apoc-procedures/src/main/java/apoc/nodes/Nodes.java:144: error: Unsupported return type <java.util.stream.Stream<java.lang.Long>> of function defined in <apoc.nodes.Nodes#loadDatabase>.`

What I return from this function which is more a procedure isn't important. At best, it could eventually returns errors.
So, what can I do ?

**Comment by sarmbruster** [comment]
The contract for procedures is to return a `Stream` of DTO (data transfer object). The DTO used for Neo4j procedure needs to have public members. The phrases used in `yield` are exactly those field names. For this reason you cannot have a `Stream<Long>`. 
For convenience, APOC contains already DTO class for most cases, e.g. there's a `[LongResult](https://github.com/neo4j-contrib/neo4j-apoc-procedures/blob/3.2/src/main/java/apoc/result/LongResult.java)`.

Since this issue is just a question and requires no further action in the code base I'm closing it off.

**Comment by ontologiae** [comment]
Thanks sarmbruster for your answer, but I tried it too, and it failed : 
```
Nodes.java:144: error: Unsupported return type <java.util.stream.Stream<apoc.result.LongResult>> of function defined in <apoc.nodes.Nodes#loadCsvRelationships>.
        public Stream<LongResult> loadCsvRelationships(@Name("path") final String csvPath, @Name("key") final String idxKey ) throws EntityNotFoundException
```

Any type I try, it fails, and it's impossible to know where it come from...
