### ISSUE TITLE
Bug - apoc.refactor.mergeNodes() encounters error

### ISSUE THREAD

**Issue by InverseFalcon** [neo4j-contrib/neo4j-apoc-procedures#578]
This demonstrates the issue:

```
CREATE (a1:Person{Name:"Steve"}) 
CREATE (a2:Person{Desc:"Football player"}) 
```

Then:

```
MATCH (a1:Person{Name:"Steve"}) 
MATCH (a2:Person{Desc:"Football player"}) 
CALL apoc.refactor.mergeNodes([a1,a2]) 
YIELD node RETURN node
```

Depending on the order of the nodes in the collection we either get (substituting the <node id> with the actual node id:

```
Node with id <node id> has been deleted in this transaction
```
or

```
Failed to invoke procedure `apoc.refactor.mergeNodes`: Caused by: org.neo4j.graphdb.NotFoundException: org.neo4j.kernel.api.exceptions.EntityNotFoundException: Unable to load NODE with id <node id>.
```

Note that if a node is looked up via an index, the error does not occur, which is why the unit test for this functionality is passing.

**Comment by kuczera** [comment]
@InverseFalcon: Any idea when this bug will be done or do you have a workaround ?

**Comment by jexp** [comment]
I think I fixed it in the head branch. Still waiting for release.

**Comment by kuczera** [comment]
Can i compile it by myself or when will we get the nect release ?

**Comment by kuczera** [comment]
On which branch can i get your fixes to compile it myself ?

**Comment by kuczera** [comment]
Checked out the head and compiled but it seems not to work:
`Failed to invoke procedure `apoc.refactor.mergeNodes`: Caused by: org.neo4j.graphdb.NotFoundException: No node with id 60498 found.`

**Comment by kuczera** [comment]
Just call me, if you need access to the test database.

**Comment by sarmbruster** [comment]
I don't think it's a bug. It's more or less the expected - but nasty - behaviour. The originating statement
```
MATCH (a1:Person{Name:"Steve"}) 
MATCH (a2:Person{Desc:"Football player"}) 
CALL apoc.refactor.mergeNodes([a1,a2]) 
YIELD node RETURN node
```

will run the `mergeNodes` upon the first hit of the match. During that a2 gets deleted. After its invocation the match is again checked since there might be more results. At that stage the a2 node is marked as deleted but still there, a check for it's `Desc` property then causes the `NotFoundException`.

One workaround would be:
```
MATCH (a1:Person{Name:"Steve"}) 
MATCH (a2:Person{Desc:"Football player"}) 
WITH * LIMIT 1
CALL apoc.refactor.mergeNodes([a1,a2]) 
YIELD node RETURN node
```
The underlying issue cannot be fixed in apoc, it's more a neo4j kernel thing.

**Comment by sarmbruster** [comment]
Closing this off since it cannot be fixed with apoc itself, see comment above.

**Comment by JHeinzde** [comment]
Hello I have the following Query: <br/> `MATCH (r:RegisteredMachine) WHERE r.whatever = {0} WITH collect(r) as nodes CALL apoc.refactor.mergeNodes(nodes) YIELD node RETURN node`
<br/>
I get the same error as in the issue, but the workaround does not apply here since I am not doing the MATCH(a1),MATCH (a2) thing. How do I workaround this with my query? Is this even possible?

**Comment by vayneYang** [comment]
@JHeinzde  I get the same error. Have you solved it? Thanks!

**Comment by kuczera** [comment]
Disable auth could work.

Am 18. Februar 2019 07:05:07 MEZ schrieb "机智杨" <notifications@github.com>:
>@JHeinzde  I get the same error. Have you solved it? Thanks!
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/578#issuecomment-464597595

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by vayneYang** [comment]
@kuczera Thanks for your reply. But I am still confused. Why it works when disable auth? And doing this will make the database vulnerable.

**Comment by JHeinzde** [comment]
@vayneYang I didnt solve it, somehow it just never appeared again shortly after I posted that problem.
