### ISSUE TITLE
Feature Request: Fulltext index on Relationship properties

### ISSUE THREAD

**Issue by dkrizic** [neo4j-contrib/neo4j-apoc-procedures#598]
The current apoc.index.addAllNodes, apocalypse.index.search does only work with Node properties. Is there a reason, that the index is not implemented for Relationship properties?

**Comment by myedibleenso** [comment]
+1

It would be very useful to have an `apoc.index.addAllRelationships` that take an index name, relationship type, and an array of properties.

It seems like the enhancement to [`apoc.index.search`](https://github.com/neo4j-contrib/neo4j-apoc-procedures/blob/591f8edba053ee92b65968f76cb68af1aece9898/src/main/java/apoc/index/FreeTextSearch.java#L102) you've proposed, @dkrizic, would require a number of changes to be able to return either nodes (`WeightedNodeResult`) or relationships (`WeightedRelationshipResult`).  Looking at the code, I don't think these two currently share a parent or mixin.  

Handing both nodes and relationships in `index.search` would be nice, though, especially since neither [`apoc.index.nodes`](https://github.com/neo4j-contrib/neo4j-apoc-procedures/blob/591f8edba053ee92b65968f76cb68af1aece9898/src/main/java/apoc/index/FulltextIndex.java#L37) nor [`apoc.index.relationships`](https://github.com/neo4j-contrib/neo4j-apoc-procedures/blob/591f8edba053ee92b65968f76cb68af1aece9898/src/main/java/apoc/index/FulltextIndex.java#L130) yield result weights/scores or support `maxNumberOfResults`.

**Comment by jexp** [comment]
As it now is in the product in 3.5.x I would close this issue?
