### ISSUE TITLE
How to install on Neo4J desktop edition

### ISSUE THREAD

**Issue by adriens** [neo4j-contrib/neo4j-apoc-procedures#704]
Hi, is it possible to install APOC on the desktop edition ?...if yes, could you please point me the guidelines ?

Thank you in advance.

Maybe should i switch back to Community Edition (which is very well documented) ?

Kind Regards,

Adrien

**Comment by InverseFalcon** [comment]
Yes, definitely possible, and very easy too!

For the db instance you want, click on Manage, and you'll see several tabbed options. Click on Plugins and you should see the option to install both APOC as well as GRAPH ALGORITHMS with a click. This should also set the necessary options in your neo4j.conf file to add APOC to your whitelist.

If you run into any trouble, let us know, otherwise close if you're satisfied!

**Comment by adriens** [comment]
AH AH AH, i've just found it !!!...indeed, it's quite easy to install now 😆 
Now, i just have to play with it.

thanks a lot !

![2017-12-26 13_16_46-neo4j desktop](https://user-images.githubusercontent.com/5235127/34344948-3340967e-ea3f-11e7-9594-f4707225d208.png)
