### ISSUE TITLE
Behaviour of apoc.subgraphNodes

### ISSUE THREAD

**Issue by Joshua-Yu** [neo4j-contrib/neo4j-apoc-procedures#711]
Hi, 

I was testing this procedure using stackoverflow data. Below is the query: 

MATCH (u:User{userId:'26'}) 
WITH u 
CALL apoc.path.subgraphNodes(u,{relationshipFilter:'POSTED>|HAS_TAG>',labelFilter:'+User+Post/Tag',maxLevel:3}) YIELD node
RETURN node

What I was trying to do is to start from a user, and find all his posts and associated tags. I expected to get User, Post and Tag nodes returned (as per labelFilter), but what I I actually got are only Tag nodes. 

Can someone please advise? 

Cheers 

Joshua
![5-01-2018 10-28-33 am](https://user-images.githubusercontent.com/34237687/34588854-4336d338-f203-11e7-8155-799729c69845.png)

**Comment by InverseFalcon** [comment]
Hi Joshua-Yu,

The `+` in label filter is a whitelist of nodes that must be in the path. The `/` in filter is a termination filter, meaning that all paths stop at the first node with that label in each path.

Your label filter is traversing through :User and :Post nodes and stopping at (and returning) :Tag nodes, so your results are as expected.

If you want :Post and :Tag nodes, then either use the `/` or the `>` filters. The `>` filter is an end node filter, similar to `/`, except traversal is allowed to continue past the node on the path.

**Comment by Joshua-Yu** [comment]
Hi Andrew,

I tested different combinations and had the following results (maxLevel is 5 and all other settings remained same): 
- '/Tag', '>Tag', '+User|Post|/Tag', '+User|Post|>Tag' ==> only Tag nodes
- '>User|Post|Tag' ==> Post and Tag nodes
- '+User|Post|Tag' ==> all nodes

I want to ensure the traversal stops at Tag node and return all nodes on the path, but it seems / or > didn't work as I expected? 

PS. the relationship is User -POSTED-> Post -> HAS_TAG -> Tag.

Best regards

Joshua

**Comment by InverseFalcon** [comment]
Hi Joshua,

The results from all of those combinations are correct. 

When there is a `/` and/or `>` present in the filter, then you will only get those nodes back. The whitelist `+` is only used to define which labels must be in the path.

The reason your second test didn't yield :User nodes is because by default the latest versions of APOC do not apply the filter to the starting node. You can enable this by supplying the following config parameter: `filterStartNode:true`

Your requirement sounds like you need a different procedure, as subgraphNodes() will only get you nodes reachable given the desired label and relationship filters. You might try `apoc.path.spanningTree()` if you're interested in only a single path to each :Tag node, then you can use `nodes(path)` to get all the nodes in the path. If you need all possible paths to :Tag nodes (instead of just the first path found to a :Tag node) then use `apoc.path.expandConfig()` instead.

**Comment by InverseFalcon** [comment]
Also, items in the filter that don't have a filter symbol implicitly use the last found symbol. So in your second example: `'>User|Post|Tag' ==> Post and Tag nodes`, since there are no symbols for Post and Tag, they will use the last found symbol, `>`, so :User, :Post, and :Tag nodes will be returned, and will be the end node for all paths found.

Anything else we can help or clarify here?

**Comment by Joshua-Yu** [comment]
Hi Andrew,

I don't have any further question for the time-being. Thanks for the time and help!

Best regards

Joshua
