### ISSUE TITLE
Feature Request: delete all nodes with labels

### ISSUE THREAD

**Issue by wadael** [neo4j-contrib/neo4j-apoc-procedures#729]
I had a need to remove all the newly and badly imported nodes after an import.
Removing all the data was out of question as I already had imported a huge quantity of data from another dataset.
One option is to do several "MATCH (n:LabelA) DETACH DELETE n", one for each label

The other is to have a procedure that takes a list of procedure names as strings and iterate on it to execute the several corresponding cypher queries.
Like 

     CALL wadael.remove.nodes.withlabel(["Activite","Categorie","Effectif","Entreprise","Etablissement","Localisation","NatureEI","NatureJuridique","Region","Responsable"])

which is quicker than x times a MATCH DETACH DELETE query

[LabelProcedure.java.txt](https://github.com/neo4j-contrib/neo4j-apoc-procedures/files/1670616/LabelProcedure.java.txt)

If you guys think it is worthy, what package should it be in, under which name 
I propose apoc.nodes.removeByLabel   (singular because only one label is needed for a node to be deleted)

**Comment by jexp** [comment]
Sounds good to me, just need to batch internally for size otherwise you get into tx-size issues.

You should also handle null both as list and value
And add backticks around the label in the cypher statement.

**Comment by jexp** [comment]
Oh and you would need to sign the Neo4j CLA https://neo4j.com/developer/cla/

**Comment by wadael** [comment]
Can you explain "just need to batch internally for size otherwise you get into tx-size issues." ?

**Comment by InverseFalcon** [comment]
@wadael When altering the graph, the graph changes have to be kept in memory for the transaction. When a large number of these build up for a transaction, you risk heap issues, including exceeding the heap size. We deal with this by batching these larger kinds of queries (see the APOC periodic procedures).

So in this case, we would want to batch the deletions. Unfortunately it's not as simple as JUST that, since a DETACH DELETE operation also deletes all relationships of the nodes being deleted. So it's not enough just to batch on the nodes being deleted, we also need to control the relationship deletion, as high numbers of relationships per node can skew the deletions being committed in the transaction (and supernodes in that set can choke the transaction).

**Comment by wadael** [comment]
Hi Andrew, thanks for the info.

If I sum up. My usage of apoc periodic, which I infered from Michael answer
is right.
He also advised a limit per transaction.
You advise to deal with the relations first.
So, would this solution be ok ?

Loop for périodic delete of relations from node with label1 till 0 lines
are changed
Then remove nodes with label1 nodes

Iterate label list and do it agzin while it lasts

Correct ?

**Comment by conker84** [comment]
Closed for lack of feedback, feel free to reopen it
