### ISSUE TITLE
[subgraphAll] relationshipFilter not expected behavior

### ISSUE THREAD

**Issue by zunio** [neo4j-contrib/neo4j-apoc-procedures#745]
```
match (n:node {id: 1})
call apoc.path.subgraphAll(n,{maxLevel:1,bfs:true, relationshipFilter:'rel_1|rel_2',labelFilter:'-label1|-label2'}) yield nodes,relationships
return nodes,relationships
```

With apoc "subgraphAll" and maxLevel=1,  the "relationshipFilter" is applied on the search of direct neighbors but not on the relationships between his neighbors.
Is this the expected behavior of this apoc?

**Apoc Version:** 3.2.3.5
**Neo4jVersion:** 3.2.6 Enterprise

**Comment by InverseFalcon** [comment]
Yes, expected behavior. The relationshipFilter only applies to expanding out to nodes. The relationships returned aren't limited by the relationshipFilter.

If you do want only a subset of the relationships between the nodes, depending on the types, then you can apply a filter to the collection of yielded relationships and only keep those of the desired types.

**Comment by zunio** [comment]
ok, maybe it would be useful, in a future version, to have a parameter that returns only the relationships listed in relationshipFilter. Maybe like the parameter filterStartNode

**Comment by InverseFalcon** [comment]
That makes sense. I'm going to close out this ticket and create a new issue requesting the feature.
