### ISSUE TITLE
Manipulate Virtual Graph - Limited/No Documentation

### ISSUE THREAD

**Issue by eWizardII** [neo4j-contrib/neo4j-apoc-procedures#749]
The documentation isn't clear on how to manipulate virtual graphs that are created by Virtual Graph
Create a graph object (map) from information that’s passed in. It’s basic structure is: `{name:"Name",properties:{properties},nodes:[nodes],relationships:[relationships]}`. E.g. How do I remove and add nodes/relationships to this new graph object that is created by the `apoc.graph.fromCypher` for example?

**Comment by jexp** [comment]
Those functions are still missing but good point to add them.

Remember that these virtual graphs are only for visualization, cypher itself cannot use them without the use of separate apoc functions.

**Comment by hoptical** [comment]
@jexp 
Are these functions still missing or they're provided in the last version?

**Comment by conker84** [comment]
we improved the documentation:
https://neo4j.com/labs/apoc/4.1/virtual/virtual-graph/

feel free to reopen in case you need additional info

**Comment by AlessioRussoIntroito** [comment]
Sorry to re-open this after two years, but I don't understand how to use concretely a virtual graph. 
Suppose I have a database with several nodes and different labels like User, Team, City and others. 
If I want to create a virtual graph to extract only Users with a particular value on a property, I can run:
```
MATCH (n:User)
WHERE n.age > 20
CALL apoc.graph.from(n, "user", {})
YIELD graph as new_graph
.. post-processing
```
If User nodes have as properties {name, age, gender, language}, how can I query **new_graph** in order to extract both:
- Gender percentage: % of male/female users
- Language count: number of users who speak English, number of users who speak Italian and so on
without matching multiple times the same User nodes?

My idea was to apply Graph Grouping APOC procedures ( apoc.nodes.group(..) ), however I cannot specify on which graph applying the grouping. 
Is there a way to define it?
