### ISSUE TITLE
apoc.periodic.iterate fails on relationship creates when {parallel:true}

### ISSUE THREAD

**Issue by kamranjon** [neo4j-contrib/neo4j-apoc-procedures#76]
Using parallel true to create many nodes using periodic.iterate works fine but using it to create relationships fails, presumably because one of the batches has a lock on the nodes being touched by one of the other parallel processes. 

Don't know enough about the internals but the resulting number of relationships that is created varies with each execution suggesting it is a race condition of this nature. 

The error produced is this:
`Failed to invoke procedure`apoc.periodic.iterate`: Caused by: java.lang.RuntimeException: Error during future.get`

Using {parallel:false} on relationship creates works as expected.

**Comment by tkroman** [comment]
@jexp one option would be employing the `TransactionTemplate` retrying on a `DeadlockDetectedException`. WDYT?

**Comment by jexp** [comment]
I think it's mostly because of deadlocks. That's why I think the easiest solution is to run with `parallel:false`

We just had a discussion about a cypher procedure that does automatic retries, e.g. with `{retries: 5}`
which could be used in iterate too.

I'm also working on improving the error reporting of iterate but it's a bit more tricky than I thought.

**Comment by kamranjon** [comment]
I think retries would be an a great solution for now.

**Comment by jexp** [comment]
Please try it out, I added support for retries. If ok, please close this issue.
