### ISSUE TITLE
Help me with apoc (mongodb)

### ISSUE THREAD

**Issue by liberioafonso** [neo4j-contrib/neo4j-apoc-procedures#830]
I'm having a problem with the APOC library, when I run the "apoc.mongodb.get" command, my NEO4J server opens connections with the mongodb server that never close. Each time the "apoc.mongodb.get" call is called, the connections accumulate until the server is overloaded.

Could you please help me with this problem?

**Comment by MikhailTrompowsky** [comment]
I'm having the same problem here. 

I'm using the apoc library to call mongodb procedure. But the connection remains. How do I can close the connection open with CALL apoc.mongodb? There's some configuration to put on neo4j.conf or some command on Neo4j Browser?

Can anyone help?

**Comment by dairton** [comment]
+1

**Comment by MrMed** [comment]
+1

**Comment by MrMed** [comment]
I find a partial answer for the problem. I look into the code of Apoc, where create the connection with mongo, and find the procedure close(), but this procedure should be implement by the extend Closure, but seems don't. But I try to close myself the connection. And on the first query.. (apoc.mongodb.first) I use try catch to close the connection. And works perfectly. But when I did for get and find method doesn't works. Because the return is different. Where do I close the connection? If I can do this, then is solved. Thanks

**Comment by jexp** [comment]
We have to do it in the onClose of the stream.

**Comment by jexp** [comment]
@omarlarus please check & confirm.
