### ISSUE TITLE
apoc.meta.graph does not display ALL relationships

### ISSUE THREAD

**Issue by adriens** [neo4j-contrib/neo4j-apoc-procedures#884]
# Runtime Configuration :

- Neo4J : 3.4.5 Enterprise
- APOC Installed 3.4.0.2

![2018-08-14 21_49_50-neo4j desktop - 1 1 8](https://user-images.githubusercontent.com/5235127/44087570-037f7760-a00c-11e8-8e6e-bf68b537dcc7.png)

![2018-08-14 21_50_29-neo4j desktop - 1 1 8](https://user-images.githubusercontent.com/5235127/44087609-1a0622c2-a00c-11e8-9155-dfa2a4f6531e.png)

# Description

i have a graph datbase with the following nodes and relationships (please note the relation between a column and a view):

![2018-08-14 21_42_53-neo4j bolt___localhost_7687 - neo4j browser](https://user-images.githubusercontent.com/5235127/44087338-440c1f78-a00b-11e8-9bac-1197e8906a7e.png)

but when i ask to apoc to show me the graph structure, i'm missing the relations between column->view

![2018-08-14 21_41_47-neo4j bolt___localhost_7687 - neo4j browser](https://user-images.githubusercontent.com/5235127/44087379-671d0f68-a00b-11e8-972e-f84068aa01e4.png)

I wonder how is this possible ?...in the documentation it is said that this procedure does not sample datas, but it looks like all nodes have not been parsed.

**Comment by adriens** [comment]
But db.schema seems to do the job :

![2018-08-14 21_53_00-neo4j bolt___localhost_7687 - neo4j browser](https://user-images.githubusercontent.com/5235127/44087768-9f5d963a-a00c-11e8-91fe-c9becd21309b.png)

**Comment by jexp** [comment]
Thanks for reporting. The problem is that the db-statistics only store half of the relationship information (only one label) so db.schema reports often false positives.

apoc.meta.graph samples a subset of the graph to confirm those relationships. In your case it seems that those `(:Column)-[:COLUMN_OF]->()` that were sampled didn't include `(:View)` and the views also didn't include those columns.

I'll check if there is an omission in the implementation.
