### ISSUE TITLE
Add generic broker integration to handle connections for SQS, RabbitMQ and Kafka

### ISSUE THREAD

**Issue by bradnussbaum** [neo4j-contrib/neo4j-apoc-procedures#905]
### Goals
The initial goal is to define a pattern for generic broker integration and start with the SQS, RabbitMQ and Kafka implementations.

### Neo4j Apoc Config
apoc.broker.<connection_name>.type=[KAFKA,RABBITMQ,SQS]
apoc.broker.<connection_name>.enabled=[true,false]
apoc.broker.<connection_name>.host=<string>
apoc.broker.<connection_name>.port=<int>
apoc.broker.<connection_name>.vhost=<string>
apoc.broker.<connection_name>.username=<string>
apoc.broker.<connection_name>.password=<string>

#### Send
This is the main broker interface for sending a message using a named connection
```
    @Procedure( mode = Mode.READ )
    @Description( "Send a message to the broker associated with the connectionName namespace. Takes in parameter which are dependent on the broker being used." )
    public Stream<BrokerMessage> send( @Name( "connectionName" ) String connectionName, @Name( "data" ) Object data,
            @Name( "parameters" ) Map<String,Object> parameters ) throws IOException
```

#### Recieve
This is the main broker interface for receiving a message using a named connection
```
    @Procedure( mode = Mode.READ )
    @Description( "Receives a message from the broker associated with the connectionName namespace. Takes in parameter which are dependent on the broker being used." )
    public Stream<BrokerMessage> receive( @Name( "connectionName" ) String connectionName
            @Name( "parameters" ) Map<String,Object> parameters ) throws IOException
```

### Parameters
```
{
  config: {
    KAFKA: {
      topic: <string>,
      offset: <int>
    },
    RABBITMQ: {
      exchange: <string>,
      queueName: <string>,
      routingKey: <string>
    },
    SQS: {
      queueName: <string>,
      region: <string>
    },
  }
}
```

**Comment by alexiudice** [comment]
Example `neo4j.conf` setup for:
-RabbitMQ broker on localhost
-RabbitMQ broker on a docker machine
-SQS broker
```apoc.broker.rmq-local.type=RABBITMQ
apoc.broker.rmq-local.enabled=true
apoc.broker.rmq-local.host=localhost
apoc.broker.rmq-local.port=5672
apoc.broker.rmq-local.vhost=/
apoc.broker.rmq-local.username=guest
apoc.broker.rmq-local.password=guest

apoc.broker.rmq-docker.type=RABBITMQ
apoc.broker.rmq-docker.enabled=true
apoc.broker.rmq-docker.host=196.168.99.100
apoc.broker.rmq-docker.port=5672
apoc.broker.rmq-docker.vhost=/
apoc.broker.rmq-docker.username=guest
apoc.broker.rmq-docker.password=guest

apoc.broker.sqs.type=SQS
apoc.broker.sqs.enabled=true
apoc.broker.sqs.access_key_id=AKJLKJSFLKJDSLF
apoc.broker.sqs.secret_key_id=iuasdjflk28787324+akjdlfk2joqu
```

With this `neo4j.conf` setup here are examples of sending messages to the brokers:

Sends a message to the localhost rabbitmq:
`CALL apoc.broker.send("rmq-local", {payload: "this is a test"}, {queueName: "queue", exchangeName: "exchange", routingKey: "routingKey"})` 

  Sends a message to the docker rabbitmq:
`CALL apoc.broker.send("rmq-docker", {payload: "this is another test"}, {queueName: "queue", exchangeName: "exchange", routingKey: "routingKey"})`

Sends a message to SQS queue `test-queue` in the region `us-west-2`:
`CALL apoc.broker.send("sqs", {payload: "this is a test for sqs"}, {queueName: "test-queue", region: "us-west-2"})`

**Comment by alexiudice** [comment]
This will be included in the `broker.adoc` but I will also drop it here. It has to do with using a configurable property `PollRecordsMax` to choose how many messages the `apoc.broker.receive` method will return.

*RabbitMQ*
PollRecordsMax working for RMQ. The apoc integration can dynamically get a configurable number of messages by using the `apoc.broker.receive` method with parameter `pollRecordsMax`, and is guaranteed to get that number of messages (or if the queue has less messages than `pollRecordsMax` it returns all the messages). I made it so setting the `pollRecordsMax` parameter to `0` gets all the messages in the queue.


*SQS*
PollRecordsMax is finicky for SQS, but that's completely due to SQS. The only way to specify consuming a dynamic number of messages is the `.withMaxNumberOfMessages( pollRecordsMax )`   method whose documentation states:
>Amazon SQS never returns more messages than this value (however, fewer messages might be returned)

For SQS the apoc integration can _theoretically_ get a configurable number of messages by using the `apoc.broker.receive` method with parameter `pollRecordsMax`, but it is not guaranteed. The documentation even says its very unreliable when having a lower number of messages in the queue.
>If the number of messages in the queue is small (less than 1000), it is likely you will get fewer messages than you requested per ReceiveMessage call.


*Kafka*
PollRecordsMax works for Kafka but it is statically set at initialization of the consumer (`poll.records.max` in Neo4j.conf), and cannot be controlled dynamically through `apoc.broker.receive`. But that statically set configuration lets `apoc.broker.receive` always get the correct number of messages from Kafka (or as many as it can if the topic does not have enough messages).

**Comment by mimomenome** [comment]
this would be really useful!

**Comment by richa-p** [comment]
Hello! Has this been released? I would like to know version of apoc jar has these procs available to send the message to a sqs?

**Comment by alexiudice** [comment]
@richa-p 
There is no official release but its in a stable and workable state.  You can pull the branches I've worked on and use gradle to build the JAR.

**Comment by richa-p** [comment]
@alexiudice Thanks so much for your response. I'll try it out.

**Comment by richa-p** [comment]
@alexiudice Could you please let me know which branch to use?

**Comment by alexiudice** [comment]
@richa-p Depends on which neo4j/apoc version you are using.

For Neo4j 3.4 you can use the branch `story-905-3.4-brokerIntegration` which is located on the GraphGrid apoc repository (`graphgrid/story-905-3.4-brokerIntegration`). 

If you're using a different Neo4j version you can use the branch `mainline-broker` on my personal apoc repository (`alexiudice/mainline-broker`). You'll need to rebase the commits in `mainline-broker` on to whichever apoc version you want to use.

**Comment by conker84** [comment]
It would be great having this into the Neo4j Stream Plugin, please consider a contribution into it, I'm closing this
