### ISSUE TITLE
Custom functions do not invalidate cache when the function changes 

### ISSUE THREAD

**Issue by garystewart** [neo4j-contrib/neo4j-apoc-procedures#927]
Hi,

I was testing the new long awaited custom function feature and noticed that the behaviour is a little strange after changing the function itself.

CALL apoc.custom.asFunction('myFunc','RETURN "test: " + $input','retVal',[['input','STRING']])
RETURN custom.myFunc ('a')
--> "test: a"

CALL apoc.custom.asFunction('myFunc','RETURN "testAGAIN: " + $input','retVal',[['input','STRING']])
RETURN custom.myFunc ('a')
--> "test: a"
This is incorrect due to the function change however the results appears to be cached and not invalidated.

RETURN custom.myFunc ('b')
--> "testAGAIN: b"
This is correct. If I restart Neo4j then the 2 above ones are correct.  Thus I am convinced that there is caching going on and not invalidated after the function itself is updated.

Am I missing something as I hope that this is not expected behaviour? :-)

Cheers,
Gary

**Comment by jexp** [comment]
Thanks a lot, Gary for testing, this is really odd. I'll check it and figure out what's wrong.

Do you run the definition and execution as two separate statements or one?
It's not clear b/c there is no semicolon after the CALL line.

**Comment by garystewart** [comment]
Separate commands via Neo4j browser.  
Also, if I run the RETURN repeatedly then it appears to still be incorrect.

**Comment by alexiudice** [comment]
It is absolutely due to the query plan cache. https://neo4j.com/developer/kb/understanding-the-query-plan-cache/

You can test this by doing the following:
First run
```
CALL apoc.custom.asFunction('myFunc','RETURN "test: " + $input','retVal',[['input','STRING']])
```

The result of `RETURN custom.myFunc ('a')` (notice the space between `myFunc` and `('a')`) is then `test:a`. 

We then redefine `myFunc` by running:
```
CALL apoc.custom.asFunction('myFunc','RETURN "testB: " + $input','retVal',[['input','STRING']])
```
Try running  `RETURN custom.myFunc ('a')` again (make sure to have the space between `myFunc` and `('a')` in the query). We get the result `test:a` which is not reflective of our new `myFunc` definition. 

Now try running `RETURN custom.myFunc('a')` Notice there is no space between the `myFunc` and `('a')`. This returns the expected result of `testB:a`. The reason the space (or lack of a space) between `myFunc` and `('a')` matters is that it produces a different hash for the query-plan cache. The query-plan cache is being used to return a cached result which corresponds to the old `myFunc`, instead of evaluating the query again with the new `myFunc`.

**Comment by jexp** [comment]
What he said. I will look into programmatically invalidating the plan case on procedure/function redefinitions. Or perhaps just add a procedure to allow it.

**Comment by garystewart** [comment]
I am currently using 3.4.7. 
If you are referring to "Remove cursor pooling on a page cache level." fix on 3.4.8 then I will try to test in the coming week if this resolved. :-)

**Comment by jexp** [comment]
@garystewart was this fixed for you?
I added an docs entry that you have to call `call dbms.clearQueryCaches()`

**Comment by garystewart** [comment]
apologies - slipped my mind - actually this is not working on 3.4.10 even when I run the call dbms.clearQueryCaches() procedure.
Is it resolved in a later version?

*I don't notice because I use a container and start fresh each time hence this cache does not 'hurt' me.
